CREATE TABLE [dbo].[AluguelGasto] (
    [ID_ALUGUEL_GASTO] INT      IDENTITY (1, 1) NOT NULL,
    [ID_CARRO]         INT      NOT NULL,
    [ID_GASTO]         INT      NOT NULL,
    [DT_ATUALIZACAO]   DATETIME NOT NULL,
    [DT_EXCLUSAO]      DATETIME NULL,
    CONSTRAINT [PK26] PRIMARY KEY NONCLUSTERED ([ID_ALUGUEL_GASTO] ASC),
    CONSTRAINT [RefCarro41] FOREIGN KEY ([ID_CARRO]) REFERENCES [dbo].[Carro] ([ID_CARRO]),
    CONSTRAINT [RefGasto42] FOREIGN KEY ([ID_GASTO]) REFERENCES [dbo].[Gasto] ([ID_GASTO])
);

