CREATE TABLE [dbo].[AvaliacaoLoja] (
    [ID_AVALIACAO_LOJA] INT  IDENTITY (1, 1) NOT NULL,
    [NR_NOTA]           INT  NOT NULL,
    [DS_COMENTARIO]     TEXT NULL,
    [ID_LOJA]           INT  NOT NULL,
    [ID_USUARIO]        INT  NOT NULL,
    CONSTRAINT [PK49] PRIMARY KEY CLUSTERED ([ID_AVALIACAO_LOJA] ASC),
    CONSTRAINT [RefLoja94] FOREIGN KEY ([ID_LOJA]) REFERENCES [dbo].[Loja] ([ID_LOJA]),
    CONSTRAINT [RefUsuario93] FOREIGN KEY ([ID_USUARIO]) REFERENCES [dbo].[Usuario] ([ID_USUARIO])
);

