CREATE TABLE [dbo].[AvaliacaoAtracao] (
    [ID_AVALIACAO_ATRACAO] INT      IDENTITY (1, 1) NOT NULL,
    [ID_USUARIO]           INT      NOT NULL,
    [ID_ATRACAO]           INT      NOT NULL,
    [NR_NOTA]              INT      NULL,
    [DS_COMENTARIO]        TEXT     NULL,
    [DT_ATUALIZACAO]       DATETIME NOT NULL,
    [DT_EXCLUSAO]          DATETIME NULL,
    CONSTRAINT [PK19_1] PRIMARY KEY NONCLUSTERED ([ID_AVALIACAO_ATRACAO] ASC),
    CONSTRAINT [RefAtracao67] FOREIGN KEY ([ID_ATRACAO]) REFERENCES [dbo].[Atracao] ([ID_ATRACAO]),
    CONSTRAINT [RefUsuario64] FOREIGN KEY ([ID_USUARIO]) REFERENCES [dbo].[Usuario] ([ID_USUARIO])
);

