CREATE TABLE [dbo].[AvaliacaoAerea] (
    [ID_AVALIACAO_AEREA] INT      IDENTITY (1, 1) NOT NULL,
    [ID_USUARIO]         INT      NOT NULL,
    [ID_VIAGEM_AEREA]    INT      NOT NULL,
    [NR_NOTA]            INT      NULL,
    [DS_COMENTARIO]      VARCHAR(MAX)     NULL,
    [DT_ATUALIZACAO]     DATETIME NOT NULL,
    [DT_EXCLUSAO]        DATETIME NULL,
    CONSTRAINT [PK19_1_2] PRIMARY KEY NONCLUSTERED ([ID_AVALIACAO_AEREA] ASC),
    CONSTRAINT [RefUsuario54] FOREIGN KEY ([ID_USUARIO]) REFERENCES [dbo].[Usuario] ([ID_USUARIO]),
    CONSTRAINT [RefViagemAerea53] FOREIGN KEY ([ID_VIAGEM_AEREA]) REFERENCES [dbo].[ViagemAerea] ([ID_VIAGEM_AEREA])
);

