CREATE TABLE [dbo].[CarroDeslocamento]
(
	ID_CARRO_DESLOCAMENTO INT IDENTITY(1,1),
	ID_CARRO INT NOT NULL,
	ID_CARRO_EVENTO_PARTIDA	INT NOT NULL,
	ID_CARRO_EVENTO_CHEGADA INT NOT NULL,
	[DT_ATUALIZACAO] DATETIME NOT NULL, 
    [DT_EXCLUSAO] DATETIME NULL, 
    [DS_OBSERVACAO] VARCHAR(MAX) NULL, 
    CONSTRAINT PK_CarroDeslocamento Primary Key(ID_CARRO_DESLOCAMENTO),
	CONSTRAINT FK_CarroDeslocamento1 Foreign Key (ID_CARRO_EVENTO_PARTIDA) REFERENCES dbo.CarroEvento(ID_CARRO_EVENTO),
	CONSTRAINT FK_CarroDeslocamento2 Foreign Key (ID_CARRO_EVENTO_CHEGADA) REFERENCES dbo.CarroEvento(ID_CARRO_EVENTO),
	CONSTRAINT FK_CarroDeslocamento3 Foreign Key (ID_CARRO) REFERENCES dbo.Carro(ID_CARRO)
)
