CREATE TABLE [dbo].[Carro] (
    [ID_CARRO]       INT          IDENTITY (1, 1) NOT NULL,
    [ID_VIAGEM]      INT          NOT NULL,
    [DS_LOCADORA]    VARCHAR (50) NULL,
    [DS_CARRO]       VARCHAR (50) NOT NULL,
    [FL_KM]          BIT          NOT NULL,
    [FL_ALUGADO]     BIT          NOT NULL,
    [DT_ATUALIZACAO] DATETIME     NOT NULL,
    [DT_EXCLUSAO]    DATETIME     NULL,
    [VL_ODOMETRO_INICIO] INT NULL, 
    [VL_ODOMETRO_FIM] INT NULL, 
    [DT_RETIRADA] DATETIME NULL, 
    [DT_DEVOLUCAO] DATETIME NULL, 
    [DS_DESCRICAO] VARCHAR(100) NOT NULL, 
    CONSTRAINT [PK24] PRIMARY KEY NONCLUSTERED ([ID_CARRO] ASC),
    CONSTRAINT [RefViagem38] FOREIGN KEY ([ID_VIAGEM]) REFERENCES [dbo].[Viagem] ([ID_VIAGEM])
);

