CREATE TABLE [dbo].[CidadeGrupo] (
    [ID_CIDADE_GRUPO] INT      IDENTITY (1, 1) NOT NULL,
    [ID_VIAGEM]       INT      NOT NULL,
    [ID_CIDADE]       INT      NOT NULL,
    [ID_CIDADE_MACRO] INT      NOT NULL,
    [DT_ATUALIZACAO]  DATETIME NOT NULL,
    [DT_EXCLUSAO]     DATETIME NULL,
    CONSTRAINT [PK11] PRIMARY KEY NONCLUSTERED ([ID_CIDADE_GRUPO] ASC),
    CONSTRAINT [RefCidade15] FOREIGN KEY ([ID_CIDADE]) REFERENCES [dbo].[Cidade] ([ID_CIDADE]),
    CONSTRAINT [RefCidade16] FOREIGN KEY ([ID_CIDADE_MACRO]) REFERENCES [dbo].[Cidade] ([ID_CIDADE]),
    CONSTRAINT [RefViagem14] FOREIGN KEY ([ID_VIAGEM]) REFERENCES [dbo].[Viagem] ([ID_VIAGEM])
);

