CREATE TABLE [dbo].[FotoRefeicao] (
    [ID_FOTO_REFEICAO] INT IDENTITY (1, 1) NOT NULL,
    [ID_FOTO]          INT NOT NULL,
    [ID_REFEICAO]      INT NOT NULL,
    CONSTRAINT [PK43] PRIMARY KEY NONCLUSTERED ([ID_FOTO_REFEICAO] ASC),
    CONSTRAINT [RefFoto76] FOREIGN KEY ([ID_FOTO]) REFERENCES [dbo].[Foto] ([ID_FOTO]),
    CONSTRAINT [RefRefeicao77] FOREIGN KEY ([ID_REFEICAO]) REFERENCES [dbo].[Refeicao] ([ID_REFEICAO])
);

