CREATE TABLE [dbo].[FotoHotel] (
    [ID_FOTO_HOTEL] INT IDENTITY (1, 1) NOT NULL,
    [ID_FOTO]       INT NOT NULL,
    [ID_HOTEL]      INT NOT NULL,
    CONSTRAINT [PK42] PRIMARY KEY NONCLUSTERED ([ID_FOTO_HOTEL] ASC),
    CONSTRAINT [RefFoto74] FOREIGN KEY ([ID_FOTO]) REFERENCES [dbo].[Foto] ([ID_FOTO]),
    CONSTRAINT [RefHotel75] FOREIGN KEY ([ID_HOTEL]) REFERENCES [dbo].[Hotel] ([ID_HOTEL])
);

