CREATE TABLE [dbo].[FotoItemCompra] (
    [ID_FOTO_ITEM_COMPRA] INT IDENTITY (1, 1) NOT NULL,
    [ID_FOTO]             INT NOT NULL,
    [ID_ITEM_COMPRA]      INT NOT NULL,
    CONSTRAINT [PK44] PRIMARY KEY NONCLUSTERED ([ID_FOTO_ITEM_COMPRA] ASC),
    CONSTRAINT [RefFoto78] FOREIGN KEY ([ID_FOTO]) REFERENCES [dbo].[Foto] ([ID_FOTO]),
    CONSTRAINT [RefItemCompra79] FOREIGN KEY ([ID_ITEM_COMPRA]) REFERENCES [dbo].[ItemCompra] ([ID_ITEM_COMPRA])
);

