CREATE TABLE [dbo].[FotoAtracao] (
    [ID_FOTO_ATRACAO] INT      IDENTITY (1, 1) NOT NULL,
    [ID_ATRACAO]      INT      NOT NULL,
    [ID_FOTO]         INT      NOT NULL,
    [DT_ATUALIZACAO]  DATETIME NOT NULL,
    [DT_EXCLUSAO]     DATETIME NULL,
    CONSTRAINT [PK41] PRIMARY KEY NONCLUSTERED ([ID_FOTO_ATRACAO] ASC),
    CONSTRAINT [RefAtracao70] FOREIGN KEY ([ID_ATRACAO]) REFERENCES [dbo].[Atracao] ([ID_ATRACAO]),
    CONSTRAINT [RefFoto71] FOREIGN KEY ([ID_FOTO]) REFERENCES [dbo].[Foto] ([ID_FOTO])
);

