CREATE TABLE [dbo].[GastoHotel] (
    [ID_GASTO_HOTEL] INT      IDENTITY (1, 1) NOT NULL,
    [ID_HOTEL]       INT      NOT NULL,
    [ID_GASTO]       INT      NOT NULL,
    [DT_ATUALIZACAO] DATETIME NOT NULL,
    [DT_EXCLUSAO]    DATETIME NULL,
    CONSTRAINT [PK18] PRIMARY KEY NONCLUSTERED ([ID_GASTO_HOTEL] ASC),
    CONSTRAINT [RefGasto31] FOREIGN KEY ([ID_GASTO]) REFERENCES [dbo].[Gasto] ([ID_GASTO]),
    CONSTRAINT [RefHotel30] FOREIGN KEY ([ID_HOTEL]) REFERENCES [dbo].[Hotel] ([ID_HOTEL])
);

