CREATE TABLE [dbo].[GastoRefeicao] (
    [ID_GASTO_REFEICAO] INT      IDENTITY (1, 1) NOT NULL,
    [ID_REFEICAO]       INT      NOT NULL,
    [ID_GASTO]          INT      NOT NULL,
    [DT_ATUALIZACAO]    DATETIME NOT NULL,
    [DT_EXCLUSAO]       DATETIME NULL,
    CONSTRAINT [PK23] PRIMARY KEY NONCLUSTERED ([ID_GASTO_REFEICAO] ASC),
    CONSTRAINT [RefGasto36] FOREIGN KEY ([ID_GASTO]) REFERENCES [dbo].[Gasto] ([ID_GASTO]),
    CONSTRAINT [RefRefeicao35] FOREIGN KEY ([ID_REFEICAO]) REFERENCES [dbo].[Refeicao] ([ID_REFEICAO])
);

