CREATE TABLE [dbo].[GastoCompra] (
    [ID_GASTO_COMPRA] INT      IDENTITY (1, 1) NOT NULL,
    [ID_LOJA]         INT      NOT NULL,
    [ID_GASTO]        INT      NOT NULL,
    [DT_ATUALIZACAO]  DATETIME NOT NULL,
    [DT_EXCLUSAO]     DATETIME NULL,
    CONSTRAINT [PK37] PRIMARY KEY NONCLUSTERED ([ID_GASTO_COMPRA] ASC),
    CONSTRAINT [RefGasto60] FOREIGN KEY ([ID_GASTO]) REFERENCES [dbo].[Gasto] ([ID_GASTO]),
    CONSTRAINT [RefLoja59] FOREIGN KEY ([ID_LOJA]) REFERENCES [dbo].[Loja] ([ID_LOJA])
);

