CREATE TABLE [dbo].[GastoAtracao]
(
	ID_GASTO_ATRACAO	 INT IDENTITY(1,1),
	ID_GASTO			INT NOT NULL,
	ID_ATRACAO			INT NOT NULL,
	DT_ATUALIZACAO		DATETIME NOT NULL,
	DT_EXCLUSAO			DATETIME	NULL,	
    CONSTRAINT [PKGastoAtracao] PRIMARY KEY NONCLUSTERED (ID_GASTO_ATRACAO ASC),
    CONSTRAINT [FKGastroAtracao1] FOREIGN KEY ([ID_GASTO]) REFERENCES [dbo].[Gasto] ([ID_GASTO]),
    CONSTRAINT [FKGastroAtracao2] FOREIGN KEY ([ID_ATRACAO]) REFERENCES [dbo].[Atracao] ([ID_ATRACAO])
)
