CREATE TABLE [dbo].[HotelEvento] (
    [ID_HOTEL_EVENTO] INT      IDENTITY (1, 1) NOT NULL,
    [ID_HOTEL]        INT      NOT NULL,
    [DT_EVENTO]       DATETIME NOT NULL,
    [CD_TIPO_EVENTO]  INT      NOT NULL,
    [DT_ATUALIZACAO]  DATETIME NOT NULL,
    CONSTRAINT [PK_HotelEvento] PRIMARY KEY CLUSTERED ([ID_HOTEL_EVENTO] ASC),
    CONSTRAINT [FK_HotelEvento1] FOREIGN KEY ([ID_HOTEL]) REFERENCES [dbo].[Hotel] ([ID_HOTEL])
);

