CREATE TABLE [dbo].[Loja] (
    [ID_LOJA]      INT             IDENTITY (1, 1) NOT NULL,
    [ID_VIAGEM]    INT             NOT NULL,
    [NM_LOJA]      VARCHAR (100)   NOT NULL,
    [NR_LATITUDE]  NUMERIC (12, 8) NOT NULL,
    [NR_LONGITUDE] NUMERIC (12, 8) NOT NULL,
    [CD_PLACE]     VARCHAR (50)    NULL,
    [DT_VISITA]    DATETIME        NOT NULL,
    [ID_ATRACAO]   INT             NULL,
    CONSTRAINT [PK36] PRIMARY KEY NONCLUSTERED ([ID_LOJA] ASC),
    CONSTRAINT [RefAtracao95] FOREIGN KEY ([ID_ATRACAO]) REFERENCES [dbo].[Atracao] ([ID_ATRACAO]),
    CONSTRAINT [RefViagem58] FOREIGN KEY ([ID_VIAGEM]) REFERENCES [dbo].[Viagem] ([ID_VIAGEM])
);

