CREATE TABLE [dbo].[Loja] (
    [ID_LOJA]        INT             IDENTITY (1, 1) NOT NULL,
    [ID_VIAGEM]      INT             NOT NULL,
    [ID_ATRACAO]     INT             NULL,
    [NM_LOJA]        VARCHAR (100)   NOT NULL,
    [NR_LATITUDE]    NUMERIC (12, 8) NULL,
    [NR_LONGITUDE]   NUMERIC (12, 8) NULL,
    [CD_PLACE]       VARCHAR (50)    NULL,
    [DT_ATUALIZACAO] DATETIME        NOT NULL,
    [DT_EXCLUSAO]    DATETIME        NULL,
    [ID_CIDADE] INT NULL, 
    CONSTRAINT [PK36] PRIMARY KEY NONCLUSTERED ([ID_LOJA] ASC),
    CONSTRAINT [RefAtracao101] FOREIGN KEY ([ID_ATRACAO]) REFERENCES [dbo].[Atracao] ([ID_ATRACAO]),
    CONSTRAINT [RefViagem58] FOREIGN KEY ([ID_VIAGEM]) REFERENCES [dbo].[Viagem] ([ID_VIAGEM]),
	CONSTRAINT [FKLoja4] FOREIGN KEY (ID_CIDADE) REFERENCES [dbo].Cidade (ID_CIDADE)
);

