CREATE TABLE [dbo].[Pais] (
    [ID_PAIS] INT          IDENTITY (1, 1) NOT NULL,
    [SG_PAIS] CHAR (3)     NOT NULL,
    [NM_PAIS] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK46] PRIMARY KEY NONCLUSTERED ([ID_PAIS] ASC)
);

