CREATE TABLE [dbo].[Posicao] (
    [ID_POSICAO]    INT             IDENTITY (1, 1) NOT NULL,
    [ID_VIAGEM]     INT             NOT NULL,
    [ID_USUARIO]    INT             NOT NULL,
    [NR_LATITUDE]   NUMERIC (12, 8) NOT NULL,
    [NR_LONGITUDE]  NUMERIC (12, 8) NOT NULL,
    [DT_GMT]        DATETIME        NOT NULL,
    [DT_LOCAL]      DATETIME        NOT NULL,
    CONSTRAINT [PK16] PRIMARY KEY NONCLUSTERED ([ID_POSICAO] ASC),
    CONSTRAINT [RefUsuario26] FOREIGN KEY ([ID_USUARIO]) REFERENCES [dbo].[Usuario] ([ID_USUARIO]),
    CONSTRAINT [RefViagem25] FOREIGN KEY ([ID_VIAGEM]) REFERENCES [dbo].[Viagem] ([ID_VIAGEM])
);

