using CV.Mobile.Models;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace CV.Mobile.Services.Api
{
    public interface IApiService
    {
        Task<UsuarioLogado> LoginGoogle(PocoLogin itemLogin);
        Task<UsuarioLogado> LogarUsuario(DadosGoogleToken DadosLogin);
        Task<UsuarioLogado> CarregarDadosAplicativo(UsuarioLogado DadosLogin);
        Task<ResultadoOperacao> SalvarUsuario(Usuario itemUsuario);
        Task<List<Viagem>> ListarViagens(CriterioBusca criterioBusca);
        Task<List<Usuario>> ListarAmigos();
        Task<List<Usuario>> ListarAmigosComigo();
        Task<UsuarioLogado> SelecionarViagem(int? IdentificadorViagem);
        Task<Viagem> CarregarViagem(int? IdentificadorViagem);
        Task<ResultadoOperacao> SalvarViagem(Viagem itemViagem);
        Task<ResultadoOperacao> SalvarViagemSimples(Viagem itemViagem);
        Task<Usuario> CarregarUsuario(int? Identificador);
        Task<Boolean> VerificarOnLine();
        Task<List<ConsultaAmigo>> ListarAmigosConsulta();
        Task<List<Amigo>> ListarAmigosUsuario();
        Task<List<RequisicaoAmizade>> ListarRequisicaoAmizade();
        Task<ResultadoOperacao> RequisicaoAmizade(ConsultaAmigo itemAmigo);
        Task<ResultadoOperacao> SalvarRequisicaoAmizade(RequisicaoAmizade itemAmigo);
        Task<List<Usuario>> ListarUsuarios(CriterioBusca criterioBusca);
        Task<List<Usuario>> ListarParticipantesViagem();
        Task<List<Usuario>> CarregarParticipantesAmigo();
        Task<ResultadoOperacao> SalvarAmigo(ConsultaAmigo itemAmigo);
        Task<List<CotacaoMoeda>> ListarCotacaoMoeda(CriterioBusca criterioBusca);
        Task<CotacaoMoeda> CarregarCotacaoMoeda(int? Identificador);
        Task<ResultadoOperacao> ExcluirCotacaoMoeda(int? Identificador);
        Task<ResultadoOperacao> SalvarCotacaoMoeda(CotacaoMoeda itemCotacaoMoeda);
        Task<List<ListaCompra>> ListarListaCompra(CriterioBusca criterioBusca);
        Task<List<ListaCompra>> ListarPedidosCompraRecebido(CriterioBusca criterioBusca);
        Task<ListaCompra> CarregarListaCompra(int? Identificador);
        Task<ResultadoOperacao> ExcluirListaCompra(int? Identificador);
        Task<ResultadoOperacao> SalvarListaCompra(ListaCompra itemPedidoCompra);
        Task<List<AporteDinheiro>> ListarAporteDinheiro(CriterioBusca criterioBusca);
        Task<AporteDinheiro> CarregarAporteDinheiro(int? Identificador);
        Task<ResultadoOperacao> ExcluirAporteDinheiro(int? Identificador);
        Task<ResultadoOperacao> SalvarAporteDinheiro(AporteDinheiro itemAporteDinheiro);
        Task<ResultadoOperacao> SalvarPosicao(Posicao itemPosicao);
        Task<List<Sugestao>> ListarSugestao(CriterioBusca criterioBusca);
        Task<List<Sugestao>> ListarSugestaoRecebida(CriterioBusca criterioBusca);
        Task<Sugestao> CarregarSugestao(int? Identificador);
        Task<ResultadoOperacao> ExcluirSugestao(int? Identificador);
        Task<ResultadoOperacao> SalvarSugestao(Sugestao itemPedidoCompra);
        Task<List<CalendarioPrevisto>> ListarCalendarioPrevisto(CriterioBusca criterioBusca);
        Task<CalendarioPrevisto> CarregarCalendarioPrevisto(int? Identificador);
        Task<ResultadoOperacao> ExcluirCalendarioPrevisto(int? Identificador);
        Task<ResultadoOperacao> SalvarCalendarioPrevisto(CalendarioPrevisto itemPedidoCompra);
        Task<ResultadoOperacao> SalvarAgendarSugestao(AgendarSugestao itemAgenda);
        Task<List<Atracao>> ListarAtracao(CriterioBusca criterioBusca);
        Task<Atracao> CarregarAtracao(int? Identificador);
        Task<ResultadoOperacao> ExcluirAtracao(int? Identificador);
        Task<ResultadoOperacao> SalvarAtracao(Atracao itemPedidoCompra);
        Task<Atracao> VerificarAtracaoAberto();
        Task<ResultadoOperacao> SalvarGastoAtracao(GastoAtracao item);
        Task<List<Gasto>> ListarGasto(CriterioBusca criterioBusca);
        Task<Gasto> CarregarGasto(int? Identificador);
        Task<ResultadoOperacao> ExcluirGasto(int? Identificador);
        Task<ResultadoOperacao> SalvarGasto(Gasto itemPedidoCompra);
        Task<List<Hotel>> ListarHotel(CriterioBusca criterioBusca);
        Task<Hotel> CarregarHotel(int? Identificador);
        Task<ResultadoOperacao> ExcluirHotel(int? Identificador);
        Task<ResultadoOperacao> SalvarHotel(Hotel itemPedidoCompra);
        Task<ResultadoOperacao> SalvarGastoHotel(GastoHotel item);
        Task<ResultadoOperacao> SalvarHotelEvento(HotelEvento item);
        Task<HotelEvento> CarregarHotelEvento(int? Identificador);
        Task<List<Refeicao>> ListarRefeicao(CriterioBusca criterioBusca);
        Task<Refeicao> CarregarRefeicao(int? Identificador);
        Task<ResultadoOperacao> ExcluirRefeicao(int? Identificador);
        Task<ResultadoOperacao> SalvarRefeicao(Refeicao itemPedidoCompra);
        Task<ResultadoOperacao> SalvarGastoRefeicao(GastoRefeicao item);
        Task<ResultadoOperacao> SalvarAluguelGasto(AluguelGasto item);
        Task<List<Comentario>> ListarComentario(CriterioBusca criterioBusca);
        Task<Comentario> CarregarComentario(int? Identificador);
        Task<ResultadoOperacao> ExcluirComentario(int? Identificador);
        Task<ResultadoOperacao> SalvarComentario(Comentario itemPedidoCompra);
        Task<List<Loja>> ListarLoja(CriterioBusca criterioBusca);
        Task<Loja> CarregarLoja(int? Identificador);
        Task<ResultadoOperacao> ExcluirLoja(int? Identificador);
        Task<ResultadoOperacao> SalvarLoja(Loja itemPedidoCompra);
        Task<ResultadoOperacao> SalvarGastoCompra(GastoCompra item);
        Task<ResultadoOperacao> ExcluirGastoCompra(GastoCompra item);
        Task<ResultadoOperacao> SalvarItemCompra(ItemCompra item);
        Task<List<ListaCompra>> CarregarListaPedidos(CriterioBusca criterioBusca);
        Task<ResultadoOperacao> ExcluirReabastecimento(int? Identificador);
        Task<ResultadoOperacao> SalvarReabastecimento(Reabastecimento itemPedidoCompra);
        Task<Reabastecimento> CarregarReabastecimento(int? Identificador);
        Task<ResultadoOperacao> SalvarCarroDeslocamento(CarroDeslocamento itemPedidoCompra);
        Task<CarroDeslocamento> CarregarCarroDeslocamento(int? Identificador);
        Task<List<Carro>> ListarCarro(CriterioBusca criterioBusca);
        Task<Carro> CarregarCarro(int? Identificador);
        Task<ResultadoOperacao> ExcluirCarro(int? Identificador);
        Task<ResultadoOperacao> SalvarCarro(Carro itemPedidoCompra);
        Task<List<ViagemAerea>> ListarViagemAerea(CriterioBusca criterioBusca);
        Task<ViagemAerea> CarregarViagemAerea(int? Identificador);
        Task<ItemCompra> CarregarItemCompra(int? Identificador);
        Task<ResultadoOperacao> ExcluirViagemAerea(int? Identificador);
        Task<ResultadoOperacao> SalvarViagemAerea(ViagemAerea itemPedidoCompra);
        Task<ResultadoOperacao> SalvarGastoViagemAerea(GastoViagemAerea item);
        Task<ResultadoOperacao> SubirImagem(UploadFoto itemUpload);
        Task<ResultadoOperacao> SubirVideo(UploadFoto itemUpload);
        Task<ClasseSincronizacao> RetornarAtualizacoes(CriterioBusca criterioBusca);
        Task<List<DeParaIdentificador>> SincronizarDados(ClasseSincronizacao itemSincronizar);
        Task<GastoAtracao> CarregarGastoAtracao(int? Identificador);
        Task<GastoHotel> CarregarGastoHotel(int? Identificador);
        Task<GastoCompra> CarregarGastoCompra(int? Identificador);
        Task<GastoRefeicao> CarregarGastoRefeicao(int? Identificador);
        Task<GastoViagemAerea> CarregarGastoViagemAerea(int? Identificador);
        Task<AluguelGasto> CarregarAluguelGasto(int? Identificador);
        Task<List<ExtratoMoeda>> ListarExtratoMoeda(CriterioBusca criterioBusca);
        Task<List<AjusteGastoDividido>> ListarAjusteGastos(CriterioBusca criterioBusca);
        Task<List<RelatorioGastos>> ListarRelatorioGastos(CriterioBusca criterioBusca);
        Task<List<CalendarioRealizado>> ConsultarCalendarioRealizado(CriterioBusca criterioBusca);
        Task<ResumoViagem> CarregarResumo(CriterioBusca criterioBusca);
        Task<List<UsuarioConsulta>> ListarAvaliacoesRankings(CriterioBusca criterioBusca);
        Task<List<LocaisVisitados>> ListarLocaisVisitados(CriterioBusca criterioBusca);
        Task<LocaisVisitados> ConsultarDetalheAtracao(CriterioBusca criterioBusca);
        Task<LocaisVisitados> ConsultarDetalheHotel(CriterioBusca criterioBusca);
        Task<LocaisVisitados> ConsultarDetalheRestaurante(CriterioBusca criterioBusca);
        Task<LocaisVisitados> ConsultarDetalheLoja(CriterioBusca criterioBusca);
        Task<List<Foto>> ListarFoto(CriterioBusca criterioBusca);
        Task<List<Atracao>> CarregarFotoAtracao();
        Task<List<Hotel>> CarregarFotoHotel();
        Task<List<Refeicao>> CarregarFotoRefeicao();
        Task<List<Timeline>> ConsultarTimeline(CriterioBusca criterioBusca);
        Task<Foto> CarregarFoto(int? Identificador);
        Task<List<PontoMapa>> ListarPontosViagem(CriterioBusca criterioBusca);
        Task<List<LinhaMapa>> ListarLinhasViagem(CriterioBusca criterioBusca);
    }
}
