//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.UI.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextosPaginas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextosPaginas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV.UI.Web.Resources.TextosPaginas", typeof(TextosPaginas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Novo.
        /// </summary>
        public static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        public static string Alterar {
            get {
                return ResourceManager.GetString("Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Senha.
        /// </summary>
        public static string AlterarSenha_ConfirmarSenha {
            get {
                return ResourceManager.GetString("AlterarSenha_ConfirmarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string AlterarSenha_Login {
            get {
                return ResourceManager.GetString("AlterarSenha_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string AlterarSenha_Nome {
            get {
                return ResourceManager.GetString("AlterarSenha_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Senha.
        /// </summary>
        public static string AlterarSenha_NovaSenha {
            get {
                return ResourceManager.GetString("AlterarSenha_NovaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Atual.
        /// </summary>
        public static string AlterarSenha_Senha {
            get {
                return ResourceManager.GetString("AlterarSenha_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Senha.
        /// </summary>
        public static string AlterarSenha_Titulo {
            get {
                return ResourceManager.GetString("AlterarSenha_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Amigo_EMail {
            get {
                return ResourceManager.GetString("Amigo_EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigo.
        /// </summary>
        public static string Amigo_IdentificadorAmigo {
            get {
                return ResourceManager.GetString("Amigo_IdentificadorAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Amigo_IdentificadorUsuario {
            get {
                return ResourceManager.GetString("Amigo_IdentificadorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Amigo_Manutencao {
            get {
                return ResourceManager.GetString("Amigo_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação.
        /// </summary>
        public static string AporteDinheiro_Cotacao {
            get {
                return ResourceManager.GetString("AporteDinheiro_Cotacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string AporteDinheiro_DataAporte {
            get {
                return ResourceManager.GetString("AporteDinheiro_DataAporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string AporteDinheiro_IdentificadorUsuario {
            get {
                return ResourceManager.GetString("AporteDinheiro_IdentificadorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string AporteDinheiro_IdentificadorViagem {
            get {
                return ResourceManager.GetString("AporteDinheiro_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string AporteDinheiro_Manutencao {
            get {
                return ResourceManager.GetString("AporteDinheiro_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeda.
        /// </summary>
        public static string AporteDinheiro_Moeda {
            get {
                return ResourceManager.GetString("AporteDinheiro_Moeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeda Estrangeira.
        /// </summary>
        public static string AporteDinheiro_MoedaEstragengeira {
            get {
                return ResourceManager.GetString("AporteDinheiro_MoedaEstragengeira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string AporteDinheiro_Valor {
            get {
                return ResourceManager.GetString("AporteDinheiro_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chegada.
        /// </summary>
        public static string Atracao_Chegada {
            get {
                return ResourceManager.GetString("Atracao_Chegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Google Place.
        /// </summary>
        public static string Atracao_CodigoPlace {
            get {
                return ResourceManager.GetString("Atracao_CodigoPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atração Pai.
        /// </summary>
        public static string Atracao_IdentificadorAtracaoPai {
            get {
                return ResourceManager.GetString("Atracao_IdentificadorAtracaoPai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Atracao_IdentificadorCidade {
            get {
                return ResourceManager.GetString("Atracao_IdentificadorCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string Atracao_IdentificadorViagem {
            get {
                return ResourceManager.GetString("Atracao_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Atracao_Latitude {
            get {
                return ResourceManager.GetString("Atracao_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Atracao_Longitude {
            get {
                return ResourceManager.GetString("Atracao_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Atracao_Manutencao {
            get {
                return ResourceManager.GetString("Atracao_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Atracao_Nome {
            get {
                return ResourceManager.GetString("Atracao_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partida.
        /// </summary>
        public static string Atracao_Partida {
            get {
                return ResourceManager.GetString("Atracao_Partida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Atracao_Tipo {
            get {
                return ResourceManager.GetString("Atracao_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Google Place.
        /// </summary>
        public static string CalendarioPrevisto_CodigoPlace {
            get {
                return ResourceManager.GetString("CalendarioPrevisto_CodigoPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string CalendarioPrevisto_Data {
            get {
                return ResourceManager.GetString("CalendarioPrevisto_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim Previsto.
        /// </summary>
        public static string CalendarioPrevisto_Fim {
            get {
                return ResourceManager.GetString("CalendarioPrevisto_Fim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string CalendarioPrevisto_IdentificadorViagem {
            get {
                return ResourceManager.GetString("CalendarioPrevisto_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início Previsto.
        /// </summary>
        public static string CalendarioPrevisto_Inicio {
            get {
                return ResourceManager.GetString("CalendarioPrevisto_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string CalendarioPrevisto_Latitude {
            get {
                return ResourceManager.GetString("CalendarioPrevisto_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string CalendarioPrevisto_Longitude {
            get {
                return ResourceManager.GetString("CalendarioPrevisto_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string CalendarioPrevisto_Manutencao {
            get {
                return ResourceManager.GetString("CalendarioPrevisto_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string CalendarioPrevisto_Nome {
            get {
                return ResourceManager.GetString("CalendarioPrevisto_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioridade.
        /// </summary>
        public static string CalendarioPrevisto_Prioridade {
            get {
                return ResourceManager.GetString("CalendarioPrevisto_Prioridade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string CalendarioPrevisto_Tipo {
            get {
                return ResourceManager.GetString("CalendarioPrevisto_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alugado.
        /// </summary>
        public static string Carro_Alugado {
            get {
                return ResourceManager.GetString("Carro_Alugado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string Carro_IdentificadorViagem {
            get {
                return ResourceManager.GetString("Carro_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM.
        /// </summary>
        public static string Carro_KM {
            get {
                return ResourceManager.GetString("Carro_KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locadora.
        /// </summary>
        public static string Carro_Locadora {
            get {
                return ResourceManager.GetString("Carro_Locadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Carro_Manutencao {
            get {
                return ResourceManager.GetString("Carro_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string Carro_Modelo {
            get {
                return ResourceManager.GetString("Carro_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Cidade_Estado {
            get {
                return ResourceManager.GetString("Cidade_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Cidade_IdentificadorPais {
            get {
                return ResourceManager.GetString("Cidade_IdentificadorPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Cidade_Manutencao {
            get {
                return ResourceManager.GetString("Cidade_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Cidade_Nome {
            get {
                return ResourceManager.GetString("Cidade_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade Filha.
        /// </summary>
        public static string CidadeGrupo_IdentificadorCidadeFilha {
            get {
                return ResourceManager.GetString("CidadeGrupo_IdentificadorCidadeFilha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade Pai.
        /// </summary>
        public static string CidadeGrupo_IdentificadorCidadePai {
            get {
                return ResourceManager.GetString("CidadeGrupo_IdentificadorCidadePai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string CidadeGrupo_IdentificadorViagem {
            get {
                return ResourceManager.GetString("CidadeGrupo_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string CidadeGrupo_Manutencao {
            get {
                return ResourceManager.GetString("CidadeGrupo_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Comentario_IdentificadorCidade {
            get {
                return ResourceManager.GetString("Comentario_IdentificadorCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string Comentario_IdentificadorViagem {
            get {
                return ResourceManager.GetString("Comentario_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Comentario_Latitude {
            get {
                return ResourceManager.GetString("Comentario_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Comentario_Longitude {
            get {
                return ResourceManager.GetString("Comentario_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Comentario_Manutencao {
            get {
                return ResourceManager.GetString("Comentario_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto.
        /// </summary>
        public static string Comentario_Texto {
            get {
                return ResourceManager.GetString("Comentario_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja excluir esse registro?.
        /// </summary>
        public static string ConfirmaExclusao {
            get {
                return ResourceManager.GetString("ConfirmaExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Cotação.
        /// </summary>
        public static string CotacaoMoeda_DataCotacao {
            get {
                return ResourceManager.GetString("CotacaoMoeda_DataCotacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string CotacaoMoeda_IdentificadorViagem {
            get {
                return ResourceManager.GetString("CotacaoMoeda_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string CotacaoMoeda_Manutencao {
            get {
                return ResourceManager.GetString("CotacaoMoeda_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeda.
        /// </summary>
        public static string CotacaoMoeda_Moeda {
            get {
                return ResourceManager.GetString("CotacaoMoeda_Moeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação.
        /// </summary>
        public static string CotacaoMoeda_ValorCotacao {
            get {
                return ResourceManager.GetString("CotacaoMoeda_ValorCotacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Foto_CodigoFoto {
            get {
                return ResourceManager.GetString("Foto_CodigoFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        public static string Foto_Comentario {
            get {
                return ResourceManager.GetString("Foto_Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Foto_Data {
            get {
                return ResourceManager.GetString("Foto_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Foto_IdentificadorCidade {
            get {
                return ResourceManager.GetString("Foto_IdentificadorCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Foto_IdentificadorUsuario {
            get {
                return ResourceManager.GetString("Foto_IdentificadorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string Foto_IdentificadorViagem {
            get {
                return ResourceManager.GetString("Foto_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Foto_Latitude {
            get {
                return ResourceManager.GetString("Foto_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Foto.
        /// </summary>
        public static string Foto_LinkFoto {
            get {
                return ResourceManager.GetString("Foto_LinkFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Thumbnail.
        /// </summary>
        public static string Foto_LinkThumbnail {
            get {
                return ResourceManager.GetString("Foto_LinkThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Foto_Longitude {
            get {
                return ResourceManager.GetString("Foto_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Foto_Manutencao {
            get {
                return ResourceManager.GetString("Foto_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Arquivo.
        /// </summary>
        public static string Foto_TipoArquivo {
            get {
                return ResourceManager.GetString("Foto_TipoArquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Foto_Video {
            get {
                return ResourceManager.GetString("Foto_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixa Dinheiro.
        /// </summary>
        public static string Gasto_ApenasBaixa {
            get {
                return ResourceManager.GetString("Gasto_ApenasBaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Gasto_Data {
            get {
                return ResourceManager.GetString("Gasto_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataPagamento.
        /// </summary>
        public static string Gasto_DataPagamento {
            get {
                return ResourceManager.GetString("Gasto_DataPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Gasto_Descricao {
            get {
                return ResourceManager.GetString("Gasto_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividido.
        /// </summary>
        public static string Gasto_Dividido {
            get {
                return ResourceManager.GetString("Gasto_Dividido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinheiro.
        /// </summary>
        public static string Gasto_Especie {
            get {
                return ResourceManager.GetString("Gasto_Especie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Gasto_IdentificadorUsuario {
            get {
                return ResourceManager.GetString("Gasto_IdentificadorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string Gasto_IdentificadorViagem {
            get {
                return ResourceManager.GetString("Gasto_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Gasto_Manutencao {
            get {
                return ResourceManager.GetString("Gasto_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeda.
        /// </summary>
        public static string Gasto_Moeda {
            get {
                return ResourceManager.GetString("Gasto_Moeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeda Estrangeira.
        /// </summary>
        public static string Gasto_MoedaEstrageira {
            get {
                return ResourceManager.GetString("Gasto_MoedaEstrageira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Gasto_Valor {
            get {
                return ResourceManager.GetString("Gasto_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Geral_Salvar {
            get {
                return ResourceManager.GetString("Geral_Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor verificar os seguintes erros.
        /// </summary>
        public static string Geral_ValidarErros {
            get {
                return ResourceManager.GetString("Geral_ValidarErros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Senha.
        /// </summary>
        public static string Home_AlterarSenha {
            get {
                return ResourceManager.GetString("Home_AlterarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigo.
        /// </summary>
        public static string Home_Amigo {
            get {
                return ResourceManager.GetString("Home_Amigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aporte Dinheiro.
        /// </summary>
        public static string Home_AporteDinheiro {
            get {
                return ResourceManager.GetString("Home_AporteDinheiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atração.
        /// </summary>
        public static string Home_Atracao {
            get {
                return ResourceManager.GetString("Home_Atracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendário Previsto.
        /// </summary>
        public static string Home_CalendarioPrevisto {
            get {
                return ResourceManager.GetString("Home_CalendarioPrevisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carro.
        /// </summary>
        public static string Home_Carro {
            get {
                return ResourceManager.GetString("Home_Carro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Home_Cidade {
            get {
                return ResourceManager.GetString("Home_Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Cidade.
        /// </summary>
        public static string Home_CidadeGrupo {
            get {
                return ResourceManager.GetString("Home_CidadeGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentário.
        /// </summary>
        public static string Home_Comentario {
            get {
                return ResourceManager.GetString("Home_Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação Moeda.
        /// </summary>
        public static string Home_CotacaoMoeda {
            get {
                return ResourceManager.GetString("Home_CotacaoMoeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Home_Dashboard {
            get {
                return ResourceManager.GetString("Home_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string Home_Foto {
            get {
                return ResourceManager.GetString("Home_Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto.
        /// </summary>
        public static string Home_Gasto {
            get {
                return ResourceManager.GetString("Home_Gasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Home_Hotel {
            get {
                return ResourceManager.GetString("Home_Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Compra.
        /// </summary>
        public static string Home_ListaCompra {
            get {
                return ResourceManager.GetString("Home_ListaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loja.
        /// </summary>
        public static string Home_Loja {
            get {
                return ResourceManager.GetString("Home_Loja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Home_Menu {
            get {
                return ResourceManager.GetString("Home_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Home_Pais {
            get {
                return ResourceManager.GetString("Home_Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posição.
        /// </summary>
        public static string Home_Posicao {
            get {
                return ResourceManager.GetString("Home_Posicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reabastecimento.
        /// </summary>
        public static string Home_Reabastecimento {
            get {
                return ResourceManager.GetString("Home_Reabastecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refeição.
        /// </summary>
        public static string Home_Refeicao {
            get {
                return ResourceManager.GetString("Home_Refeicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisição Amizade.
        /// </summary>
        public static string Home_RequisicaoAmizade {
            get {
                return ResourceManager.GetString("Home_RequisicaoAmizade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugestão.
        /// </summary>
        public static string Home_Sugestao {
            get {
                return ResourceManager.GetString("Home_Sugestao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Home_Usuario {
            get {
                return ResourceManager.GetString("Home_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string Home_Viagem {
            get {
                return ResourceManager.GetString("Home_Viagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem Aérea.
        /// </summary>
        public static string Home_ViagemAerea {
            get {
                return ResourceManager.GetString("Home_ViagemAerea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Google Place.
        /// </summary>
        public static string Hotel_CodigoPlace {
            get {
                return ResourceManager.GetString("Hotel_CodigoPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Entrada.
        /// </summary>
        public static string Hotel_DataEntrada {
            get {
                return ResourceManager.GetString("Hotel_DataEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saída.
        /// </summary>
        public static string Hotel_DataSaidia {
            get {
                return ResourceManager.GetString("Hotel_DataSaidia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada Prevista.
        /// </summary>
        public static string Hotel_EntradaPrevista {
            get {
                return ResourceManager.GetString("Hotel_EntradaPrevista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Hotel_IdentificadorCidade {
            get {
                return ResourceManager.GetString("Hotel_IdentificadorCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string Hotel_IdentificadorViagem {
            get {
                return ResourceManager.GetString("Hotel_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Hotel_Latitude {
            get {
                return ResourceManager.GetString("Hotel_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Hotel_Longitude {
            get {
                return ResourceManager.GetString("Hotel_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Hotel_Manutencao {
            get {
                return ResourceManager.GetString("Hotel_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Hotel_Nome {
            get {
                return ResourceManager.GetString("Hotel_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saída Prevista.
        /// </summary>
        public static string Hotel_SaidaPrevista {
            get {
                return ResourceManager.GetString("Hotel_SaidaPrevista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprado.
        /// </summary>
        public static string ListaCompra_Comprado {
            get {
                return ResourceManager.GetString("ListaCompra_Comprado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string ListaCompra_Descricao {
            get {
                return ResourceManager.GetString("ListaCompra_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatário.
        /// </summary>
        public static string ListaCompra_Destinatario {
            get {
                return ResourceManager.GetString("ListaCompra_Destinatario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string ListaCompra_IdentificadorUsuario {
            get {
                return ResourceManager.GetString("ListaCompra_IdentificadorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário Pedido.
        /// </summary>
        public static string ListaCompra_IdentificadorUsuarioPedido {
            get {
                return ResourceManager.GetString("ListaCompra_IdentificadorUsuarioPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string ListaCompra_IdentificadorViagem {
            get {
                return ResourceManager.GetString("ListaCompra_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string ListaCompra_Manutencao {
            get {
                return ResourceManager.GetString("ListaCompra_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string ListaCompra_Marca {
            get {
                return ResourceManager.GetString("ListaCompra_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeda.
        /// </summary>
        public static string ListaCompra_Moeda {
            get {
                return ResourceManager.GetString("ListaCompra_Moeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reembolsavel.
        /// </summary>
        public static string ListaCompra_Reembolsavel {
            get {
                return ResourceManager.GetString("ListaCompra_Reembolsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Máximo.
        /// </summary>
        public static string ListaCompra_ValorMaximo {
            get {
                return ResourceManager.GetString("ListaCompra_ValorMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logar.
        /// </summary>
        public static string Login_Logar {
            get {
                return ResourceManager.GetString("Login_Logar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Login_Senha {
            get {
                return ResourceManager.GetString("Login_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Place.
        /// </summary>
        public static string Loja_CodigoPlace {
            get {
                return ResourceManager.GetString("Loja_CodigoPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Loja_Data {
            get {
                return ResourceManager.GetString("Loja_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atração.
        /// </summary>
        public static string Loja_IdentificadorAtracao {
            get {
                return ResourceManager.GetString("Loja_IdentificadorAtracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string Loja_IdentificadorViagem {
            get {
                return ResourceManager.GetString("Loja_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Loja_Latitude {
            get {
                return ResourceManager.GetString("Loja_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Loja_Longitude {
            get {
                return ResourceManager.GetString("Loja_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Loja_Manutencao {
            get {
                return ResourceManager.GetString("Loja_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Loja_Nome {
            get {
                return ResourceManager.GetString("Loja_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Nao {
            get {
                return ResourceManager.GetString("Nao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Pais_Manutencao {
            get {
                return ResourceManager.GetString("Pais_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Pais_Nome {
            get {
                return ResourceManager.GetString("Pais_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla.
        /// </summary>
        public static string Pais_Sigla {
            get {
                return ResourceManager.GetString("Pais_Sigla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string Pesquisar {
            get {
                return ResourceManager.GetString("Pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGMT.
        /// </summary>
        public static string Posicao_DataGMT {
            get {
                return ResourceManager.GetString("Posicao_DataGMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Local.
        /// </summary>
        public static string Posicao_DataLocal {
            get {
                return ResourceManager.GetString("Posicao_DataLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Posicao_IdentificadorUsuario {
            get {
                return ResourceManager.GetString("Posicao_IdentificadorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string Posicao_IdentificadorViagem {
            get {
                return ResourceManager.GetString("Posicao_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Posicao_Latitude {
            get {
                return ResourceManager.GetString("Posicao_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Posicao_Longitude {
            get {
                return ResourceManager.GetString("Posicao_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Posicao_Manutencao {
            get {
                return ResourceManager.GetString("Posicao_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidade.
        /// </summary>
        public static string Posicao_Velocidade {
            get {
                return ResourceManager.GetString("Posicao_Velocidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carro.
        /// </summary>
        public static string Reabastecimento_IdentificadorCarro {
            get {
                return ResourceManager.GetString("Reabastecimento_IdentificadorCarro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Reabastecimento_IdentificadorCidade {
            get {
                return ResourceManager.GetString("Reabastecimento_IdentificadorCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Reabastecimento_Latitude {
            get {
                return ResourceManager.GetString("Reabastecimento_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litro.
        /// </summary>
        public static string Reabastecimento_Litro {
            get {
                return ResourceManager.GetString("Reabastecimento_Litro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Reabastecimento_Longitude {
            get {
                return ResourceManager.GetString("Reabastecimento_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Reabastecimento_Manutencao {
            get {
                return ResourceManager.GetString("Reabastecimento_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade Reabastecida.
        /// </summary>
        public static string Reabastecimento_QuantidadeReabastecida {
            get {
                return ResourceManager.GetString("Reabastecimento_QuantidadeReabastecida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Place.
        /// </summary>
        public static string Refeicao_CodigoPlace {
            get {
                return ResourceManager.GetString("Refeicao_CodigoPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Refeicao_Data {
            get {
                return ResourceManager.GetString("Refeicao_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atração.
        /// </summary>
        public static string Refeicao_IdentificadorAtracao {
            get {
                return ResourceManager.GetString("Refeicao_IdentificadorAtracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Refeicao_IdentificadorCidade {
            get {
                return ResourceManager.GetString("Refeicao_IdentificadorCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string Refeicao_IdentificadorViagem {
            get {
                return ResourceManager.GetString("Refeicao_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Refeicao_Latitude {
            get {
                return ResourceManager.GetString("Refeicao_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Refeicao_Longitude {
            get {
                return ResourceManager.GetString("Refeicao_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Refeicao_Manutencao {
            get {
                return ResourceManager.GetString("Refeicao_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurante.
        /// </summary>
        public static string Refeicao_Nome {
            get {
                return ResourceManager.GetString("Refeicao_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Refeicao_Tipo {
            get {
                return ResourceManager.GetString("Refeicao_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMail.
        /// </summary>
        public static string RequisicaoAmizade_EMail {
            get {
                return ResourceManager.GetString("RequisicaoAmizade_EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string RequisicaoAmizade_IdentificadorUsuario {
            get {
                return ResourceManager.GetString("RequisicaoAmizade_IdentificadorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Requisitado.
        /// </summary>
        public static string RequisicaoAmizade_IdentificadorUsuarioRequisitado {
            get {
                return ResourceManager.GetString("RequisicaoAmizade_IdentificadorUsuarioRequisitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string RequisicaoAmizade_Manutencao {
            get {
                return ResourceManager.GetString("RequisicaoAmizade_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RequisicaoAmizade_Status {
            get {
                return ResourceManager.GetString("RequisicaoAmizade_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Sair {
            get {
                return ResourceManager.GetString("Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string Selecione {
            get {
                return ResourceManager.GetString("Selecione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Sim {
            get {
                return ResourceManager.GetString("Sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentário.
        /// </summary>
        public static string Sugestao_Comentario {
            get {
                return ResourceManager.GetString("Sugestao_Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Sugestao_IdentificadorCidade {
            get {
                return ResourceManager.GetString("Sugestao_IdentificadorCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Sugestao_IdentificadorUsuario {
            get {
                return ResourceManager.GetString("Sugestao_IdentificadorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string Sugestao_IdentificadorViagem {
            get {
                return ResourceManager.GetString("Sugestao_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Sugestao_Latitude {
            get {
                return ResourceManager.GetString("Sugestao_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lida.
        /// </summary>
        public static string Sugestao_Lida {
            get {
                return ResourceManager.GetString("Sugestao_Lida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string Sugestao_Local {
            get {
                return ResourceManager.GetString("Sugestao_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Sugestao_Longitude {
            get {
                return ResourceManager.GetString("Sugestao_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Sugestao_Manutencao {
            get {
                return ResourceManager.GetString("Sugestao_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Sugestao_Tipo {
            get {
                return ResourceManager.GetString("Sugestao_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV.
        /// </summary>
        public static string TituloAplicacao {
            get {
                return ResourceManager.GetString("TituloAplicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV.
        /// </summary>
        public static string TituloAplicacaoReduzido {
            get {
                return ResourceManager.GetString("TituloAplicacaoReduzido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último Acesso: .
        /// </summary>
        public static string UltimoAcesso {
            get {
                return ResourceManager.GetString("UltimoAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        public static string Usuario_Codigo {
            get {
                return ResourceManager.GetString("Usuario_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Usuario_DataToken {
            get {
                return ResourceManager.GetString("Usuario_DataToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Usuario_EMail {
            get {
                return ResourceManager.GetString("Usuario_EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string Usuario_Identificador {
            get {
                return ResourceManager.GetString("Usuario_Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime.
        /// </summary>
        public static string Usuario_Lifetime {
            get {
                return ResourceManager.GetString("Usuario_Lifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Usuario_Manutencao {
            get {
                return ResourceManager.GetString("Usuario_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Usuario_Nome {
            get {
                return ResourceManager.GetString("Usuario_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshToken.
        /// </summary>
        public static string Usuario_RefreshToken {
            get {
                return ResourceManager.GetString("Usuario_RefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Usuario_Token {
            get {
                return ResourceManager.GetString("Usuario_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aberto.
        /// </summary>
        public static string Viagem_Aberto {
            get {
                return ResourceManager.GetString("Viagem_Aberto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim.
        /// </summary>
        public static string Viagem_DataFim {
            get {
                return ResourceManager.GetString("Viagem_DataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Início.
        /// </summary>
        public static string Viagem_DataInicio {
            get {
                return ResourceManager.GetString("Viagem_DataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Viagem_IdentificadorUsuario {
            get {
                return ResourceManager.GetString("Viagem_IdentificadorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string Viagem_Manutencao {
            get {
                return ResourceManager.GetString("Viagem_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeda.
        /// </summary>
        public static string Viagem_Moeda {
            get {
                return ResourceManager.GetString("Viagem_Moeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Viagem_Nome {
            get {
                return ResourceManager.GetString("Viagem_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual IOF.
        /// </summary>
        public static string Viagem_PercentualIOF {
            get {
                return ResourceManager.GetString("Viagem_PercentualIOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastos Públicos.
        /// </summary>
        public static string Viagem_PublicaGasto {
            get {
                return ResourceManager.GetString("Viagem_PublicaGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade Participantes.
        /// </summary>
        public static string Viagem_QuantidadeParticipantes {
            get {
                return ResourceManager.GetString("Viagem_QuantidadeParticipantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade Métrica.
        /// </summary>
        public static string Viagem_UnidadeMetrica {
            get {
                return ResourceManager.GetString("Viagem_UnidadeMetrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanhiaAerea.
        /// </summary>
        public static string ViagemAerea_CompanhiaAerea {
            get {
                return ResourceManager.GetString("ViagemAerea_CompanhiaAerea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFim.
        /// </summary>
        public static string ViagemAerea_DataFim {
            get {
                return ResourceManager.GetString("ViagemAerea_DataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataInicio.
        /// </summary>
        public static string ViagemAerea_DataInicio {
            get {
                return ResourceManager.GetString("ViagemAerea_DataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataPrevista.
        /// </summary>
        public static string ViagemAerea_DataPrevista {
            get {
                return ResourceManager.GetString("ViagemAerea_DataPrevista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        public static string ViagemAerea_IdentificadorViagem {
            get {
                return ResourceManager.GetString("ViagemAerea_IdentificadorViagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manutenção.
        /// </summary>
        public static string ViagemAerea_Manutencao {
            get {
                return ResourceManager.GetString("ViagemAerea_Manutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string Voltar {
            get {
                return ResourceManager.GetString("Voltar", resourceCulture);
            }
        }
    }
}
