//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV.Mobile.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para essa operação é necessário estar conectado na internet..
        /// </summary>
        internal static string AplicacaoOnlineNecessaria {
            get {
                return ResourceManager.GetString("AplicacaoOnlineNecessaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtindo uma Viagem.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atração.
        /// </summary>
        internal static string Atracao {
            get {
                return ResourceManager.GetString("Atracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A atração {0} está sendo visitada, deseja associar a nova atração como filha dela?.
        /// </summary>
        internal static string AtracaoAberta {
            get {
                return ResourceManager.GetString("AtracaoAberta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitando atração {0}.
        /// </summary>
        internal static string AtracaoVisita {
            get {
                return ResourceManager.GetString("AtracaoVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor preencher o campo..
        /// </summary>
        internal static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja cancelar a edição. Itens não salvos serão perdidos..
        /// </summary>
        internal static string CancelarEdicao {
            get {
                return ResourceManager.GetString("CancelarEdicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movendo-se de carro {0}.
        /// </summary>
        internal static string CarroDeslocamento {
            get {
                return ResourceManager.GetString("CarroDeslocamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devolução do carro {0} para locadora {1}.
        /// </summary>
        internal static string CarroDevolucao {
            get {
                return ResourceManager.GetString("CarroDevolucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reabasteceu carro {0}.
        /// </summary>
        internal static string CarroReabastecido {
            get {
                return ResourceManager.GetString("CarroReabastecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirada do carro {0} na locadora {1}.
        /// </summary>
        internal static string CarroRetirada {
            get {
                return ResourceManager.GetString("CarroRetirada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companhia de Transporte.
        /// </summary>
        internal static string CompanhiaTransporte {
            get {
                return ResourceManager.GetString("CompanhiaTransporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário estar conectado na internet para executar essa função.
        /// </summary>
        internal static string ConexaoInternetObrigatoria {
            get {
                return ResourceManager.GetString("ConexaoInternetObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração Salva com Sucesso.
        /// </summary>
        internal static string ConfiguracaoSalvaSucesso {
            get {
                return ResourceManager.GetString("ConfiguracaoSalvaSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        internal static string Confirmacao {
            get {
                return ResourceManager.GetString("Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        internal static string Continuar {
            get {
                return ResourceManager.GetString("Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custo Existente.
        /// </summary>
        internal static string CustoExistente {
            get {
                return ResourceManager.GetString("CustoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao desmarcar essa pessoa você deixará de acompanhar suas viagens. Deseja remover?.
        /// </summary>
        internal static string DesmarcarSeguido {
            get {
                return ResourceManager.GetString("DesmarcarSeguido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao desmarcar essa pessoa como seguidora ela deixará de visualizar suas viagens. Deseja desmarcá-la?.
        /// </summary>
        internal static string DesmarcarSeguidora {
            get {
                return ResourceManager.GetString("DesmarcarSeguidora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja excluir a aquisição de moeda {0} {1}?.
        /// </summary>
        internal static string ExcluirAquisicaoMoeda {
            get {
                return ResourceManager.GetString("ExcluirAquisicaoMoeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja excluir a atração {0}?.
        /// </summary>
        internal static string ExcluirAtracao {
            get {
                return ResourceManager.GetString("ExcluirAtracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja excluir o comentário?.
        /// </summary>
        internal static string ExcluirComentario {
            get {
                return ResourceManager.GetString("ExcluirComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja excluir a cotação de {0} para {1}?.
        /// </summary>
        internal static string ExcluirCotacao {
            get {
                return ResourceManager.GetString("ExcluirCotacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja excluir o deslocamento {0}?.
        /// </summary>
        internal static string ExcluirDeslocamento {
            get {
                return ResourceManager.GetString("ExcluirDeslocamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja excluir o gasto {0} de {1}{2}?.
        /// </summary>
        internal static string ExcluirGasto {
            get {
                return ResourceManager.GetString("ExcluirGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja excluir a hospedagem {0}?.
        /// </summary>
        internal static string ExcluirHotel {
            get {
                return ResourceManager.GetString("ExcluirHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja excluir a refeição {0}?.
        /// </summary>
        internal static string ExcluirRefeição {
            get {
                return ResourceManager.GetString("ExcluirRefeição", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão realizada com sucesso..
        /// </summary>
        internal static string ExclusaoSucesso {
            get {
                return ResourceManager.GetString("ExclusaoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        internal static string Foto {
            get {
                return ResourceManager.GetString("Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hora final deve ser maior que a data de início..
        /// </summary>
        internal static string HoraFimMaiorDataInicio {
            get {
                return ResourceManager.GetString("HoraFimMaiorDataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        internal static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fez check in na hospedagem {0}.
        /// </summary>
        internal static string HotelCheckIn {
            get {
                return ResourceManager.GetString("HotelCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fez check out da hospedagem {0}.
        /// </summary>
        internal static string HotelCheckOut {
            get {
                return ResourceManager.GetString("HotelCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descansando na hospedagem {0}.
        /// </summary>
        internal static string HotelNoHotel {
            get {
                return ResourceManager.GetString("HotelNoHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locadora.
        /// </summary>
        internal static string Locadora {
            get {
                return ResourceManager.GetString("Locadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loja.
        /// </summary>
        internal static string Loja {
            get {
                return ResourceManager.GetString("Loja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fez compras na loja {0}.
        /// </summary>
        internal static string LojaCompra {
            get {
                return ResourceManager.GetString("LojaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido.
        /// </summary>
        internal static string MailInvalido {
            get {
                return ResourceManager.GetString("MailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data deve ser maior que a data início..
        /// </summary>
        internal static string MaiorDataInicio {
            get {
                return ResourceManager.GetString("MaiorDataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao marcar essa pessoa será enviada uma solicitação para você visualizar suas viagens. Deseja continuar?.
        /// </summary>
        internal static string MarcarSeguido {
            get {
                return ResourceManager.GetString("MarcarSeguido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao marcar essa pessoa como seguidora ela poderá visualizar suas viagens. Deseja marcá-la?.
        /// </summary>
        internal static string MarcarSeguidora {
            get {
                return ResourceManager.GetString("MarcarSeguidora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O acesso foi expirado.
        /// </summary>
        internal static string MensagemAutenticacao {
            get {
                return ResourceManager.GetString("MensagemAutenticacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mídia salva com sucesso..
        /// </summary>
        internal static string MidiaSalvaSucesso {
            get {
                return ResourceManager.GetString("MidiaSalvaSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        internal static string Nao {
            get {
                return ResourceManager.GetString("Nao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Custo.
        /// </summary>
        internal static string NovoCusto {
            get {
                return ResourceManager.GetString("NovoCusto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qual ponto deseja ajustar?.
        /// </summary>
        internal static string PontoAjustar {
            get {
                return ResourceManager.GetString("PontoAjustar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim.
        /// </summary>
        internal static string PontoFim {
            get {
                return ResourceManager.GetString("PontoFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        internal static string PontoInicio {
            get {
                return ResourceManager.GetString("PontoInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemas.
        /// </summary>
        internal static string Problemas {
            get {
                return ResourceManager.GetString("Problemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A atração {0} está em visita, deseja adicionar a refeição como filho desta?.
        /// </summary>
        internal static string RefeicaoAtracaoAberta {
            get {
                return ResourceManager.GetString("RefeicaoAtracaoAberta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comendo {0} no restaurante {1}.
        /// </summary>
        internal static string RefeicaoFazendo {
            get {
                return ResourceManager.GetString("RefeicaoFazendo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caso seja reprovada a requisição essa pessoa só poderá visualizar suas viagens se fizer uma nova solicitação. Deseja continuar?.
        /// </summary>
        internal static string ReprovarRequisicao {
            get {
                return ResourceManager.GetString("ReprovarRequisicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurante.
        /// </summary>
        internal static string Restaurante {
            get {
                return ResourceManager.GetString("Restaurante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        internal static string Sim {
            get {
                return ResourceManager.GetString("Sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronização.
        /// </summary>
        internal static string Sincronizacao {
            get {
                return ResourceManager.GetString("Sincronizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        internal static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que custo deseja adicionar?.
        /// </summary>
        internal static string TipoCustoAdicionar {
            get {
                return ResourceManager.GetString("TipoCustoAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Mídia.
        /// </summary>
        internal static string TipoMidia {
            get {
                return ResourceManager.GetString("TipoMidia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja trocar a viagem selecionada para a viagem criada?.
        /// </summary>
        internal static string TrocarViagemSelecionada {
            get {
                return ResourceManager.GetString("TrocarViagemSelecionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluindo deslocamento {0} em {1}.
        /// </summary>
        internal static string ViagemAereaDestino {
            get {
                return ResourceManager.GetString("ViagemAereaDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazendo escala de {0} em {1}.
        /// </summary>
        internal static string ViagemAereaEscala {
            get {
                return ResourceManager.GetString("ViagemAereaEscala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando inicio do deslocamento {0} em {1}.
        /// </summary>
        internal static string ViagemAereaOrigem {
            get {
                return ResourceManager.GetString("ViagemAereaOrigem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viajando {0}.
        /// </summary>
        internal static string ViagemAereaViajando {
            get {
                return ResourceManager.GetString("ViagemAereaViajando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vídeo.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        internal static string Voltar {
            get {
                return ResourceManager.GetString("Voltar", resourceCulture);
            }
        }
    }
}
