//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Business.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV.Business.Resources.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você deixou de seguir essa pessoa..
        /// </summary>
        internal static string AbandonarSeguido {
            get {
                return ResourceManager.GetString("AbandonarSeguido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário {0} não tem permissão de acesso a atividade {1}..
        /// </summary>
        internal static string AcessoTelaNegado {
            get {
                return ResourceManager.GetString("AcessoTelaNegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deseja ser seu amigo para visualizar suas viagens..
        /// </summary>
        internal static string AlertaRequisicaoAmizade {
            get {
                return ResourceManager.GetString("AlertaRequisicaoAmizade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} recomenda a visita a {1} durante sua viagem..
        /// </summary>
        internal static string AlertaSugestaoVisita {
            get {
                return ResourceManager.GetString("AlertaSugestaoVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado não é válido..
        /// </summary>
        internal static string Amigo_MailInvalido {
            get {
                return ResourceManager.GetString("Amigo_MailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário preencher o e-mail de seu amigo..
        /// </summary>
        internal static string Amigo_MailObrigatorio {
            get {
                return ResourceManager.GetString("Amigo_MailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário selecionar o tipo de amizade a ser associado..
        /// </summary>
        internal static string Amigo_TipoAmizade {
            get {
                return ResourceManager.GetString("Amigo_TipoAmizade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não pode se adicionar como amigo..
        /// </summary>
        internal static string Amigo_UsuarioAtual {
            get {
                return ResourceManager.GetString("Amigo_UsuarioAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigo adicionado como seguidor..
        /// </summary>
        internal static string AmigoAdicionado {
            get {
                return ResourceManager.GetString("AmigoAdicionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa removida como seguidora..
        /// </summary>
        internal static string AmigoRemovido {
            get {
                return ResourceManager.GetString("AmigoRemovido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Moeda Baixa é obrigatório..
        /// </summary>
        internal static string AporteDinheiro_MoedaGasto {
            get {
                return ResourceManager.GetString("AporteDinheiro_MoedaGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Valor Baixa é obrigatório..
        /// </summary>
        internal static string AporteDinheiro_ValorGasto {
            get {
                return ResourceManager.GetString("AporteDinheiro_ValorGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor definir a data de Partida.
        /// </summary>
        internal static string CarroDeslocamento_DataPartida_Obrigatoria {
            get {
                return ResourceManager.GetString("CarroDeslocamento_DataPartida_Obrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor definir a posição de Chegada.
        /// </summary>
        internal static string CarroDeslocamento_PosicaoChegada_Obrigatoria {
            get {
                return ResourceManager.GetString("CarroDeslocamento_PosicaoChegada_Obrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor definir a posição de Partida.
        /// </summary>
        internal static string CarroDeslocamento_PosicaoPartida_Obrigatoria {
            get {
                return ResourceManager.GetString("CarroDeslocamento_PosicaoPartida_Obrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser selecionada ao menos uma cidade como pertencente ao grupo.
        /// </summary>
        internal static string CidadeGrupo_CidadeFilhaAssociada {
            get {
                return ResourceManager.GetString("CidadeGrupo_CidadeFilhaAssociada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Cidade Principal é obrigatório.
        /// </summary>
        internal static string CidadeGrupo_CidadePai {
            get {
                return ResourceManager.GetString("CidadeGrupo_CidadePai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cidade principal já está associada a outro agrupamento de cidades.
        /// </summary>
        internal static string CidadeGrupo_CidadePaiUtilizada {
            get {
                return ResourceManager.GetString("CidadeGrupo_CidadePaiUtilizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tela já se encontra aberta. Deseja fechá-la e abrir uma nova..
        /// </summary>
        internal static string ConfirmacaoAberturaTela {
            get {
                return ResourceManager.GetString("ConfirmacaoAberturaTela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro durante o processamento da requisição. Tentar novamente e caso não obtenha sucesso, entrar em contato com a área de suporte.
        /// </summary>
        internal static string DescricaoAmigavelErro {
            get {
                return ResourceManager.GetString("DescricaoAmigavelErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realmente deseja excluir o registro selecionado?.
        /// </summary>
        internal static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário que haja uma linha selecionada no grid para executar essa ação..
        /// </summary>
        internal static string NecessarioSelecionarItemGrid {
            get {
                return ResourceManager.GetString("NecessarioSelecionarItemGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV.
        /// </summary>
        internal static string NomeSistema {
            get {
                return ResourceManager.GetString("NomeSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Pedir Para é obrigatório.
        /// </summary>
        internal static string PedidoCompra_PedirParaObrigatorio {
            get {
                return ResourceManager.GetString("PedidoCompra_PedirParaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisição Aprovada, o usuário agora pode acompanhar suas viagens..
        /// </summary>
        internal static string Requisicao_Aprovada {
            get {
                return ResourceManager.GetString("Requisicao_Aprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisição Reprovada.
        /// </summary>
        internal static string Requisicao_Reprovada {
            get {
                return ResourceManager.GetString("Requisicao_Reprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi enviada a sua requisição de amizade..
        /// </summary>
        internal static string RequisicaoAmizade {
            get {
                return ResourceManager.GetString("RequisicaoAmizade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigo.
        /// </summary>
        internal static string Tela_Amigo {
            get {
                return ResourceManager.GetString("Tela_Amigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aporte Dinheiro.
        /// </summary>
        internal static string Tela_AporteDinheiro {
            get {
                return ResourceManager.GetString("Tela_AporteDinheiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atração.
        /// </summary>
        internal static string Tela_Atracao {
            get {
                return ResourceManager.GetString("Tela_Atracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendário Previsto.
        /// </summary>
        internal static string Tela_CalendarioPrevisto {
            get {
                return ResourceManager.GetString("Tela_CalendarioPrevisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carro.
        /// </summary>
        internal static string Tela_Carro {
            get {
                return ResourceManager.GetString("Tela_Carro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        internal static string Tela_Cidade {
            get {
                return ResourceManager.GetString("Tela_Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Cidade.
        /// </summary>
        internal static string Tela_CidadeGrupo {
            get {
                return ResourceManager.GetString("Tela_CidadeGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentário.
        /// </summary>
        internal static string Tela_Comentario {
            get {
                return ResourceManager.GetString("Tela_Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação Moeda.
        /// </summary>
        internal static string Tela_CotacaoMoeda {
            get {
                return ResourceManager.GetString("Tela_CotacaoMoeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        internal static string Tela_Foto {
            get {
                return ResourceManager.GetString("Tela_Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto.
        /// </summary>
        internal static string Tela_Gasto {
            get {
                return ResourceManager.GetString("Tela_Gasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        internal static string Tela_Hotel {
            get {
                return ResourceManager.GetString("Tela_Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Compra.
        /// </summary>
        internal static string Tela_ListaCompra {
            get {
                return ResourceManager.GetString("Tela_ListaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loja.
        /// </summary>
        internal static string Tela_Loja {
            get {
                return ResourceManager.GetString("Tela_Loja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string Tela_Pais {
            get {
                return ResourceManager.GetString("Tela_Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posição.
        /// </summary>
        internal static string Tela_Posicao {
            get {
                return ResourceManager.GetString("Tela_Posicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reabastecimento.
        /// </summary>
        internal static string Tela_Reabastecimento {
            get {
                return ResourceManager.GetString("Tela_Reabastecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refeição.
        /// </summary>
        internal static string Tela_Refeicao {
            get {
                return ResourceManager.GetString("Tela_Refeicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisição Amizade.
        /// </summary>
        internal static string Tela_RequisicaoAmizade {
            get {
                return ResourceManager.GetString("Tela_RequisicaoAmizade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugestão.
        /// </summary>
        internal static string Tela_Sugestao {
            get {
                return ResourceManager.GetString("Tela_Sugestao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        internal static string Tela_Usuario {
            get {
                return ResourceManager.GetString("Tela_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem.
        /// </summary>
        internal static string Tela_Viagem {
            get {
                return ResourceManager.GetString("Tela_Viagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem Aérea.
        /// </summary>
        internal static string Tela_ViagemAerea {
            get {
                return ResourceManager.GetString("Tela_ViagemAerea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de Página.
        /// </summary>
        internal static string TituloErro {
            get {
                return ResourceManager.GetString("TituloErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erros Validação.
        /// </summary>
        internal static string TituloPopupErro {
            get {
                return ResourceManager.GetString("TituloPopupErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário {0}  não tem permissão Acesso ao Sistema..
        /// </summary>
        internal static string UsuarioSemPermissao {
            get {
                return ResourceManager.GetString("UsuarioSemPermissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirAluguelGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAluguelGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigo excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirAmigo_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAmigo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aporte de Dinheiro excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirAporteDinheiro_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAporteDinheiro_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atração excluída com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de AvaliacaoAerea foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirAvaliacaoAerea_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAvaliacaoAerea_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de AvaliacaoAluguel foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirAvaliacaoAluguel_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAvaliacaoAluguel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de AvaliacaoAtracao foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirAvaliacaoAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAvaliacaoAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de AvaliacaoLoja foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirAvaliacaoLoja_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAvaliacaoLoja_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agemdamento excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirCalendarioPrevisto_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirCalendarioPrevisto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carro excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirCarro_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirCarro_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deslocamento excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirCarroDeslocamento_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirCarroDeslocamento_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de CarroEvento foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirCarroEvento_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirCarroEvento_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de Cidade foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirCidade_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirCidade_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrupamento de Cidades excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirCidadeGrupo_Lista_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirCidadeGrupo_Lista_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de CidadeGrupo foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirCidadeGrupo_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirCidadeGrupo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentário excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirComentario_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirComentario_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação de Moeda excluída com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirCotacaoMoeda_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirCotacaoMoeda_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto excluída com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirFoto_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirFoto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de FotoAtracao foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirFotoAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirFotoAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de FotoHotel foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirFotoHotel_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirFotoHotel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de FotoItemCompra foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirFotoItemCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirFotoItemCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de FotoRefeicao foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirFotoRefeicao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirFotoRefeicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirGastoAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGastoAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra excluída com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirGastoCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGastoCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de Gasto Dividido foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirGastoDividido_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGastoDividido_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirGastoHotel_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGastoHotel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirGastoPosicao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGastoPosicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirGastoRefeicao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGastoRefeicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirGastoViagemAerea_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGastoViagemAerea_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de Hotel foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirHotel_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirHotel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de HotelAvaliacao foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirHotelAvaliacao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirHotelAvaliacao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirHotelEvento_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirHotelEvento_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item da Compra excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirItemCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirItemCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista excluída com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirListaCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirListaCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loja excluída com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirLoja_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirLoja_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de Pais foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirPais_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirPais_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de ParticipanteViagem foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirParticipanteViagem_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirParticipanteViagem_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de Posicao foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirPosicao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirPosicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reabastecimento excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirReabastecimento_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirReabastecimento_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de ReabastecimentoGasto foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirReabastecimentoGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirReabastecimentoGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refeição excluída com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirRefeicao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirRefeicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de RefeicaoPedido foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirRefeicaoPedido_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirRefeicaoPedido_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de RequisicaoAmizade foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirRequisicaoAmizade_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirRequisicaoAmizade_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugestão excluída com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirSugestao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirSugestao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de Usuario foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirUsuario_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirUsuario_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de UsuarioGasto foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirUsuarioGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirUsuarioGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem excluída com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirViagem_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirViagem_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deslocamento excluído com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirViagemAerea_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirViagemAerea_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de ViagemAereaAeroporto foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_ExcluirViagemAereaAeroporto_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirViagemAereaAeroporto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarAluguelGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAluguelGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigo salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarAmigo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAmigo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aporte de Dinheiro salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarAporteDinheiro_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAporteDinheiro_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Atracao foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarAtracao_Completo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAtracao_Completo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atração salva com sucesso.
        /// </summary>
        internal static string Viagem_SalvarAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Atracao foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarAtracaoCompleto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAtracaoCompleto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de AvaliacaoAerea foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarAvaliacaoAerea_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAvaliacaoAerea_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de AvaliacaoAluguel foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarAvaliacaoAluguel_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAvaliacaoAluguel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de AvaliacaoAtracao foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarAvaliacaoAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAvaliacaoAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de AvaliacaoLoja foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarAvaliacaoLoja_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAvaliacaoLoja_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agendamento salvo com sucesso..
        /// </summary>
        internal static string Viagem_SalvarCalendarioPrevisto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCalendarioPrevisto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Carro foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarCarro_Completo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCarro_Completo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carro salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarCarro_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCarro_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deslocamento salvo com sucesso..
        /// </summary>
        internal static string Viagem_SalvarCarroDeslocamento_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCarroDeslocamento_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de CarroEvento foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarCarroEvento_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCarroEvento_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Cidade foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarCidade_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCidade_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrupamento de Cidade salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarCidadeGrupo_Lista_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCidadeGrupo_Lista_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Agrupamento de Cidades foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarCidadeGrupo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCidadeGrupo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentário salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarComentario_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarComentario_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação de Moeda salva com sucesso.
        /// </summary>
        internal static string Viagem_SalvarCotacaoMoeda_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCotacaoMoeda_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Foto foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarFoto_Completa_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarFoto_Completa_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto salvar com sucesso.
        /// </summary>
        internal static string Viagem_SalvarFoto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarFoto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de FotoAtracao foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarFotoAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarFotoAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de FotoHotel foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarFotoHotel_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarFotoHotel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de FotoItemCompra foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarFotoItemCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarFotoItemCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de FotoRefeicao foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarFotoRefeicao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarFotoRefeicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Gasto foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarGasto_Completo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGasto_Completo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarGastoAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra salva com sucesso.
        /// </summary>
        internal static string Viagem_SalvarGastoCompra_Item_Completo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoCompra_Item_Completo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra salva com sucesso.
        /// </summary>
        internal static string Viagem_SalvarGastoCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Gasto Dividido foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarGastoDividido_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoDividido_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarGastoHotel_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoHotel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarGastoPosicao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoPosicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarGastoRefeicao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoRefeicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasto salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarGastoViagemAerea_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoViagemAerea_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Hotel foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarHotel_Completo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarHotel_Completo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Hotel foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarHotel_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarHotel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de HotelAvaliacao foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarHotelAvaliacao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarHotelAvaliacao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarHotelEvento_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarHotelEvento_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item da Compra salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarItemCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarItemCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Compra salva com sucesso.
        /// </summary>
        internal static string Viagem_SalvarListaCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarListaCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loja salva com sucesso.
        /// </summary>
        internal static string Viagem_SalvarLoja_Completo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarLoja_Completo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loja salva com sucesso.
        /// </summary>
        internal static string Viagem_SalvarLoja_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarLoja_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Pais foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarPais_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarPais_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de ParticipanteViagem foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarParticipanteViagem_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarParticipanteViagem_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Posicao foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarPosicao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarPosicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reabastecimento salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarReabastecimento_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarReabastecimento_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de ReabastecimentoGasto foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarReabastecimentoGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarReabastecimentoGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Refeicao foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarRefeicao_Completo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarRefeicao_Completo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Refeição salva com sucesso.
        /// </summary>
        internal static string Viagem_SalvarRefeicao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarRefeicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de RefeicaoPedido foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarRefeicaoPedido_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarRefeicaoPedido_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de RequisicaoAmizade foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarRequisicaoAmizade_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarRequisicaoAmizade_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugestão salva com sucesso.
        /// </summary>
        internal static string Viagem_SalvarSugestao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarSugestao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Usuario foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarUsuario_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarUsuario_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de UsuarioGasto foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarUsuarioGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarUsuarioGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de Viagem foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarViagem_Completa_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarViagem_Completa_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viagem salva com sucesso.
        /// </summary>
        internal static string Viagem_SalvarViagem_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarViagem_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de ViagemAerea foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarViagemAerea_Completa_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarViagemAerea_Completa_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deslocamento salvo com sucesso.
        /// </summary>
        internal static string Viagem_SalvarViagemAerea_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarViagemAerea_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravação de ViagemAereaAeroporto foi realizada com sucesso.
        /// </summary>
        internal static string Viagem_SalvarViagemAereaAeroporto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarViagemAereaAeroporto_OK", resourceCulture);
            }
        }
    }
}
