//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.8689
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Business.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar seqüências de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV.Business.Resources.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Você deixou de seguir essa pessoa..
        /// </summary>
        public static string AbandonarSeguido {
            get {
                return ResourceManager.GetString("AbandonarSeguido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a O usuário {0} não tem permissão de acesso a atividade {1}..
        /// </summary>
        public static string AcessoTelaNegado {
            get {
                return ResourceManager.GetString("AcessoTelaNegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a {0} deseja ser seu amigo para visualizar suas viagens..
        /// </summary>
        public static string AlertaRequisicaoAmizade {
            get {
                return ResourceManager.GetString("AlertaRequisicaoAmizade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a O e-mail informado não é válido..
        /// </summary>
        public static string Amigo_MailInvalido {
            get {
                return ResourceManager.GetString("Amigo_MailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a É necessário preencher o e-mail de seu amigo..
        /// </summary>
        public static string Amigo_MailObrigatorio {
            get {
                return ResourceManager.GetString("Amigo_MailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a É necessário selecionar o tipo de amizade a ser associado..
        /// </summary>
        public static string Amigo_TipoAmizade {
            get {
                return ResourceManager.GetString("Amigo_TipoAmizade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Você não pode se adicionar como amigo..
        /// </summary>
        public static string Amigo_UsuarioAtual {
            get {
                return ResourceManager.GetString("Amigo_UsuarioAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Amigo adicionado como seguidor..
        /// </summary>
        public static string AmigoAdicionado {
            get {
                return ResourceManager.GetString("AmigoAdicionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Pessoa removida como seguidora..
        /// </summary>
        public static string AmigoRemovido {
            get {
                return ResourceManager.GetString("AmigoRemovido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a A tela já se encontra aberta. Deseja fechá-la e abrir uma nova..
        /// </summary>
        public static string ConfirmacaoAberturaTela {
            get {
                return ResourceManager.GetString("ConfirmacaoAberturaTela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Ocorreu um erro durante o processamento da requisição. Tentar novamente e caso não obtenha sucesso, entrar em contato com a área de suporte.
        /// </summary>
        public static string DescricaoAmigavelErro {
            get {
                return ResourceManager.GetString("DescricaoAmigavelErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Realmente deseja excluir o registro selecionado?.
        /// </summary>
        public static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a É necessário que haja uma linha selecionada no grid para executar essa ação..
        /// </summary>
        public static string NecessarioSelecionarItemGrid {
            get {
                return ResourceManager.GetString("NecessarioSelecionarItemGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a CV.
        /// </summary>
        public static string NomeSistema {
            get {
                return ResourceManager.GetString("NomeSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Requisição Aprovada, o usuário agora pode acompanhar suas viagens..
        /// </summary>
        public static string Requisicao_Aprovada {
            get {
                return ResourceManager.GetString("Requisicao_Aprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Requisição Reprovada.
        /// </summary>
        public static string Requisicao_Reprovada {
            get {
                return ResourceManager.GetString("Requisicao_Reprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Foi enviada a sua requisição de amizade..
        /// </summary>
        public static string RequisicaoAmizade {
            get {
                return ResourceManager.GetString("RequisicaoAmizade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Amigo.
        /// </summary>
        public static string Tela_Amigo {
            get {
                return ResourceManager.GetString("Tela_Amigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Aporte Dinheiro.
        /// </summary>
        public static string Tela_AporteDinheiro {
            get {
                return ResourceManager.GetString("Tela_AporteDinheiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Atração.
        /// </summary>
        public static string Tela_Atracao {
            get {
                return ResourceManager.GetString("Tela_Atracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Calendário Previsto.
        /// </summary>
        public static string Tela_CalendarioPrevisto {
            get {
                return ResourceManager.GetString("Tela_CalendarioPrevisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Carro.
        /// </summary>
        public static string Tela_Carro {
            get {
                return ResourceManager.GetString("Tela_Carro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Cidade.
        /// </summary>
        public static string Tela_Cidade {
            get {
                return ResourceManager.GetString("Tela_Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Grupo Cidade.
        /// </summary>
        public static string Tela_CidadeGrupo {
            get {
                return ResourceManager.GetString("Tela_CidadeGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Comentário.
        /// </summary>
        public static string Tela_Comentario {
            get {
                return ResourceManager.GetString("Tela_Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Cotação Moeda.
        /// </summary>
        public static string Tela_CotacaoMoeda {
            get {
                return ResourceManager.GetString("Tela_CotacaoMoeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Foto.
        /// </summary>
        public static string Tela_Foto {
            get {
                return ResourceManager.GetString("Tela_Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gasto.
        /// </summary>
        public static string Tela_Gasto {
            get {
                return ResourceManager.GetString("Tela_Gasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Hotel.
        /// </summary>
        public static string Tela_Hotel {
            get {
                return ResourceManager.GetString("Tela_Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Lista de Compra.
        /// </summary>
        public static string Tela_ListaCompra {
            get {
                return ResourceManager.GetString("Tela_ListaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Loja.
        /// </summary>
        public static string Tela_Loja {
            get {
                return ResourceManager.GetString("Tela_Loja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a País.
        /// </summary>
        public static string Tela_Pais {
            get {
                return ResourceManager.GetString("Tela_Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Posição.
        /// </summary>
        public static string Tela_Posicao {
            get {
                return ResourceManager.GetString("Tela_Posicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Reabastecimento.
        /// </summary>
        public static string Tela_Reabastecimento {
            get {
                return ResourceManager.GetString("Tela_Reabastecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Refeição.
        /// </summary>
        public static string Tela_Refeicao {
            get {
                return ResourceManager.GetString("Tela_Refeicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Requisição Amizade.
        /// </summary>
        public static string Tela_RequisicaoAmizade {
            get {
                return ResourceManager.GetString("Tela_RequisicaoAmizade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Sugestão.
        /// </summary>
        public static string Tela_Sugestao {
            get {
                return ResourceManager.GetString("Tela_Sugestao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Usuário.
        /// </summary>
        public static string Tela_Usuario {
            get {
                return ResourceManager.GetString("Tela_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Viagem.
        /// </summary>
        public static string Tela_Viagem {
            get {
                return ResourceManager.GetString("Tela_Viagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Viagem Aérea.
        /// </summary>
        public static string Tela_ViagemAerea {
            get {
                return ResourceManager.GetString("Tela_ViagemAerea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Erro de Página.
        /// </summary>
        public static string TituloErro {
            get {
                return ResourceManager.GetString("TituloErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Erros Validação.
        /// </summary>
        public static string TituloPopupErro {
            get {
                return ResourceManager.GetString("TituloPopupErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a O usuário {0}  não tem permissão Acesso ao Sistema..
        /// </summary>
        public static string UsuarioSemPermissao {
            get {
                return ResourceManager.GetString("UsuarioSemPermissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de AluguelGasto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirAluguelGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAluguelGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Amigo foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirAmigo_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAmigo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de AporteDinheiro foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirAporteDinheiro_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAporteDinheiro_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Atracao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de AvaliacaoAerea foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirAvaliacaoAerea_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAvaliacaoAerea_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de AvaliacaoAluguel foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirAvaliacaoAluguel_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAvaliacaoAluguel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de AvaliacaoAtracao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirAvaliacaoAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAvaliacaoAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de AvaliacaoLoja foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirAvaliacaoLoja_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirAvaliacaoLoja_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de CalendarioPrevisto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirCalendarioPrevisto_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirCalendarioPrevisto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Carro foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirCarro_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirCarro_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de CarroEvento foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirCarroEvento_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirCarroEvento_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Cidade foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirCidade_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirCidade_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de CidadeGrupo foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirCidadeGrupo_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirCidadeGrupo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Comentario foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirComentario_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirComentario_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de CotacaoMoeda foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirCotacaoMoeda_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirCotacaoMoeda_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Foto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirFoto_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirFoto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de FotoAtracao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirFotoAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirFotoAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de FotoHotel foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirFotoHotel_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirFotoHotel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de FotoItemCompra foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirFotoItemCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirFotoItemCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de FotoRefeicao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirFotoRefeicao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirFotoRefeicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Gasto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de GastoAtracao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirGastoAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGastoAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de GastoCompra foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirGastoCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGastoCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Gasto Dividido foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirGastoDividido_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGastoDividido_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de GastoHotel foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirGastoHotel_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGastoHotel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de GastoPosicao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirGastoPosicao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGastoPosicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de GastoRefeicao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirGastoRefeicao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGastoRefeicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de GastoViagemAerea foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirGastoViagemAerea_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirGastoViagemAerea_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Hotel foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirHotel_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirHotel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de HotelAvaliacao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirHotelAvaliacao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirHotelAvaliacao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de HotelEvento foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirHotelEvento_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirHotelEvento_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de ItemCompra foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirItemCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirItemCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de ListaCompra foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirListaCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirListaCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Loja foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirLoja_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirLoja_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Pais foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirPais_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirPais_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de ParticipanteViagem foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirParticipanteViagem_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirParticipanteViagem_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Posicao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirPosicao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirPosicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de AluguelReabastecimento foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirReabastecimento_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirReabastecimento_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de ReabastecimentoGasto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirReabastecimentoGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirReabastecimentoGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Refeicao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirRefeicao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirRefeicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de RefeicaoPedido foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirRefeicaoPedido_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirRefeicaoPedido_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de RequisicaoAmizade foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirRequisicaoAmizade_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirRequisicaoAmizade_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Sugestao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirSugestao_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirSugestao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Usuario foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirUsuario_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirUsuario_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de UsuarioGasto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirUsuarioGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirUsuarioGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de Viagem foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirViagem_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirViagem_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de ViagemAerea foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirViagemAerea_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirViagemAerea_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Exclusão de ViagemAereaAeroporto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_ExcluirViagemAereaAeroporto_OK {
            get {
                return ResourceManager.GetString("Viagem_ExcluirViagemAereaAeroporto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de AluguelGasto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarAluguelGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAluguelGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Amigo foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarAmigo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAmigo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de AporteDinheiro foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarAporteDinheiro_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAporteDinheiro_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Atracao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarAtracao_Completo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAtracao_Completo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Atracao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Atracao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarAtracaoCompleto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAtracaoCompleto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de AvaliacaoAerea foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarAvaliacaoAerea_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAvaliacaoAerea_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de AvaliacaoAluguel foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarAvaliacaoAluguel_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAvaliacaoAluguel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de AvaliacaoAtracao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarAvaliacaoAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAvaliacaoAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de AvaliacaoLoja foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarAvaliacaoLoja_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarAvaliacaoLoja_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de CalendarioPrevisto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarCalendarioPrevisto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCalendarioPrevisto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Carro foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarCarro_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCarro_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de CarroEvento foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarCarroEvento_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCarroEvento_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Cidade foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarCidade_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCidade_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de CidadeGrupo foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarCidadeGrupo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCidadeGrupo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Comentario foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarComentario_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarComentario_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de CotacaoMoeda foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarCotacaoMoeda_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarCotacaoMoeda_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Foto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarFoto_Completa_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarFoto_Completa_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Foto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarFoto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarFoto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de FotoAtracao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarFotoAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarFotoAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de FotoHotel foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarFotoHotel_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarFotoHotel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de FotoItemCompra foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarFotoItemCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarFotoItemCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de FotoRefeicao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarFotoRefeicao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarFotoRefeicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Gasto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarGasto_Completo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGasto_Completo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Gasto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de GastoAtracao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarGastoAtracao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoAtracao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de GastoCompra foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarGastoCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Gasto Dividido foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarGastoDividido_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoDividido_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de GastoHotel foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarGastoHotel_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoHotel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de GastoPosicao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarGastoPosicao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoPosicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de GastoRefeicao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarGastoRefeicao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoRefeicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de GastoViagemAerea foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarGastoViagemAerea_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarGastoViagemAerea_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Hotel foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarHotel_Completo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarHotel_Completo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Hotel foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarHotel_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarHotel_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de HotelAvaliacao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarHotelAvaliacao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarHotelAvaliacao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de HotelEvento foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarHotelEvento_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarHotelEvento_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de ItemCompra foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarItemCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarItemCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de ListaCompra foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarListaCompra_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarListaCompra_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Loja foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarLoja_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarLoja_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Pais foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarPais_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarPais_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de ParticipanteViagem foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarParticipanteViagem_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarParticipanteViagem_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Posicao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarPosicao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarPosicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de AluguelReabastecimento foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarReabastecimento_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarReabastecimento_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de ReabastecimentoGasto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarReabastecimentoGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarReabastecimentoGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Refeicao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarRefeicao_Completo_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarRefeicao_Completo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Refeicao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarRefeicao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarRefeicao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de RefeicaoPedido foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarRefeicaoPedido_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarRefeicaoPedido_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de RequisicaoAmizade foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarRequisicaoAmizade_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarRequisicaoAmizade_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Sugestao foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarSugestao_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarSugestao_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Usuario foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarUsuario_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarUsuario_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de UsuarioGasto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarUsuarioGasto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarUsuarioGasto_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Viagem foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarViagem_Completa_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarViagem_Completa_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de Viagem foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarViagem_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarViagem_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de ViagemAerea foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarViagemAerea_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarViagemAerea_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Gravação de ViagemAereaAeroporto foi realizada com sucesso.
        /// </summary>
        public static string Viagem_SalvarViagemAereaAeroporto_OK {
            get {
                return ResourceManager.GetString("Viagem_SalvarViagemAereaAeroporto_OK", resourceCulture);
            }
        }
    }
}
