//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.8689
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Model.Resource {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar seqüências de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumDescription() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV.Model.Resource.EnumDescription", typeof(EnumDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DIRHAM/EMIR.ARABE.
        /// </summary>
        public static string enumMoeda_AED {
            get {
                return ResourceManager.GetString("enumMoeda_AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LEK ALBANIA REP.
        /// </summary>
        public static string enumMoeda_ALL {
            get {
                return ResourceManager.GetString("enumMoeda_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DRAM ARMENIA REP.
        /// </summary>
        public static string enumMoeda_AMD {
            get {
                return ResourceManager.GetString("enumMoeda_AMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a GUILDER ANTILHAS HOLANDESAS.
        /// </summary>
        public static string enumMoeda_ANG {
            get {
                return ResourceManager.GetString("enumMoeda_ANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a KWANZA/ANGOLA.
        /// </summary>
        public static string enumMoeda_AOA {
            get {
                return ResourceManager.GetString("enumMoeda_AOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a PESO ARGENTINO.
        /// </summary>
        public static string enumMoeda_ARS {
            get {
                return ResourceManager.GetString("enumMoeda_ARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR AUSTRALIANO.
        /// </summary>
        public static string enumMoeda_AUD {
            get {
                return ResourceManager.GetString("enumMoeda_AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a FLORIM/ARUBA.
        /// </summary>
        public static string enumMoeda_AWG {
            get {
                return ResourceManager.GetString("enumMoeda_AWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a MANAT ARZEBAIJAO.
        /// </summary>
        public static string enumMoeda_AZN {
            get {
                return ResourceManager.GetString("enumMoeda_AZN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a MARCO CONV BOSNIA.
        /// </summary>
        public static string enumMoeda_BAM {
            get {
                return ResourceManager.GetString("enumMoeda_BAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR/BARBADOS.
        /// </summary>
        public static string enumMoeda_BBD {
            get {
                return ResourceManager.GetString("enumMoeda_BBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a TACA/BANGLADESH.
        /// </summary>
        public static string enumMoeda_BDT {
            get {
                return ResourceManager.GetString("enumMoeda_BDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LEV/BULGARIA, REP.
        /// </summary>
        public static string enumMoeda_BGN {
            get {
                return ResourceManager.GetString("enumMoeda_BGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DINAR/BAHREIN.
        /// </summary>
        public static string enumMoeda_BHD {
            get {
                return ResourceManager.GetString("enumMoeda_BHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a FRANCO/BURUNDI.
        /// </summary>
        public static string enumMoeda_BIF {
            get {
                return ResourceManager.GetString("enumMoeda_BIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR/BERMUDAS.
        /// </summary>
        public static string enumMoeda_BMD {
            get {
                return ResourceManager.GetString("enumMoeda_BMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR BRUNEI.
        /// </summary>
        public static string enumMoeda_BND {
            get {
                return ResourceManager.GetString("enumMoeda_BND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a BOLIVIANO/BOLIVIA.
        /// </summary>
        public static string enumMoeda_BOB {
            get {
                return ResourceManager.GetString("enumMoeda_BOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a REAL BRASIL.
        /// </summary>
        public static string enumMoeda_BRL {
            get {
                return ResourceManager.GetString("enumMoeda_BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR/BAHAMAS.
        /// </summary>
        public static string enumMoeda_BSD {
            get {
                return ResourceManager.GetString("enumMoeda_BSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a NGULTRUM/BUTAO.
        /// </summary>
        public static string enumMoeda_BTN {
            get {
                return ResourceManager.GetString("enumMoeda_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a PULA/BOTSWANA.
        /// </summary>
        public static string enumMoeda_BWP {
            get {
                return ResourceManager.GetString("enumMoeda_BWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RUBLO BELARUS.
        /// </summary>
        public static string enumMoeda_BYN {
            get {
                return ResourceManager.GetString("enumMoeda_BYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR/BELIZE.
        /// </summary>
        public static string enumMoeda_BZD {
            get {
                return ResourceManager.GetString("enumMoeda_BZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR CANADENSE.
        /// </summary>
        public static string enumMoeda_CAD {
            get {
                return ResourceManager.GetString("enumMoeda_CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a FRANCO CONGOLES.
        /// </summary>
        public static string enumMoeda_CDF {
            get {
                return ResourceManager.GetString("enumMoeda_CDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a FRANCO SUICO.
        /// </summary>
        public static string enumMoeda_CHF {
            get {
                return ResourceManager.GetString("enumMoeda_CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a UNIDADE DE FOMENTO DO CHILE.
        /// </summary>
        public static string enumMoeda_CLF {
            get {
                return ResourceManager.GetString("enumMoeda_CLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a PESO CHILE.
        /// </summary>
        public static string enumMoeda_CLP {
            get {
                return ResourceManager.GetString("enumMoeda_CLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RENMINBI HONG KONG.
        /// </summary>
        public static string enumMoeda_CNH {
            get {
                return ResourceManager.GetString("enumMoeda_CNH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RENMIMBI IUAN.
        /// </summary>
        public static string enumMoeda_CNY {
            get {
                return ResourceManager.GetString("enumMoeda_CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a PESO/COLOMBIA.
        /// </summary>
        public static string enumMoeda_COP {
            get {
                return ResourceManager.GetString("enumMoeda_COP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a COLON/COSTA RICA.
        /// </summary>
        public static string enumMoeda_CRC {
            get {
                return ResourceManager.GetString("enumMoeda_CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a PESO/CUBA.
        /// </summary>
        public static string enumMoeda_CUP {
            get {
                return ResourceManager.GetString("enumMoeda_CUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a ESCUDO CABO VERDE.
        /// </summary>
        public static string enumMoeda_CVE {
            get {
                return ResourceManager.GetString("enumMoeda_CVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a COROA TCHECA.
        /// </summary>
        public static string enumMoeda_CZK {
            get {
                return ResourceManager.GetString("enumMoeda_CZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a FRANCO/DJIBUTI.
        /// </summary>
        public static string enumMoeda_DJF {
            get {
                return ResourceManager.GetString("enumMoeda_DJF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a COROA DINAMARQUESA.
        /// </summary>
        public static string enumMoeda_DKK {
            get {
                return ResourceManager.GetString("enumMoeda_DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a PESO/REP. DOMINIC.
        /// </summary>
        public static string enumMoeda_DOP {
            get {
                return ResourceManager.GetString("enumMoeda_DOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DINAR ARGELINO.
        /// </summary>
        public static string enumMoeda_DZD {
            get {
                return ResourceManager.GetString("enumMoeda_DZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LIBRA/EGITO.
        /// </summary>
        public static string enumMoeda_EGP {
            get {
                return ResourceManager.GetString("enumMoeda_EGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a NAKFA ERITREIA.
        /// </summary>
        public static string enumMoeda_ERN {
            get {
                return ResourceManager.GetString("enumMoeda_ERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a BIRR/ETIOPIA.
        /// </summary>
        public static string enumMoeda_ETB {
            get {
                return ResourceManager.GetString("enumMoeda_ETB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a EURO.
        /// </summary>
        public static string enumMoeda_EUR {
            get {
                return ResourceManager.GetString("enumMoeda_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR FIJI.
        /// </summary>
        public static string enumMoeda_FJD {
            get {
                return ResourceManager.GetString("enumMoeda_FJD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LIBRA/FALKLAND.
        /// </summary>
        public static string enumMoeda_FKP {
            get {
                return ResourceManager.GetString("enumMoeda_FKP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LIBRA ESTERLINA.
        /// </summary>
        public static string enumMoeda_GBP {
            get {
                return ResourceManager.GetString("enumMoeda_GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LARI GEORGIA.
        /// </summary>
        public static string enumMoeda_GEL {
            get {
                return ResourceManager.GetString("enumMoeda_GEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a CEDI GANA.
        /// </summary>
        public static string enumMoeda_GHS {
            get {
                return ResourceManager.GetString("enumMoeda_GHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LIBRA/GIBRALTAR.
        /// </summary>
        public static string enumMoeda_GIP {
            get {
                return ResourceManager.GetString("enumMoeda_GIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DALASI/GAMBIA.
        /// </summary>
        public static string enumMoeda_GMD {
            get {
                return ResourceManager.GetString("enumMoeda_GMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a FRANCO/GUINE.
        /// </summary>
        public static string enumMoeda_GNF {
            get {
                return ResourceManager.GetString("enumMoeda_GNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a QUETZAL/GUATEMALA.
        /// </summary>
        public static string enumMoeda_GTQ {
            get {
                return ResourceManager.GetString("enumMoeda_GTQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a PESO/GUINE BISSAU.
        /// </summary>
        public static string enumMoeda_GWP {
            get {
                return ResourceManager.GetString("enumMoeda_GWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR DA GUIANA.
        /// </summary>
        public static string enumMoeda_GYD {
            get {
                return ResourceManager.GetString("enumMoeda_GYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR HONG KONG.
        /// </summary>
        public static string enumMoeda_HKD {
            get {
                return ResourceManager.GetString("enumMoeda_HKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LEMPIRA/HONDURAS.
        /// </summary>
        public static string enumMoeda_HNL {
            get {
                return ResourceManager.GetString("enumMoeda_HNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a KUNA/CROACIA.
        /// </summary>
        public static string enumMoeda_HRK {
            get {
                return ResourceManager.GetString("enumMoeda_HRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a GOURDE/HAITI.
        /// </summary>
        public static string enumMoeda_HTG {
            get {
                return ResourceManager.GetString("enumMoeda_HTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a FORINT/HUNGRIA.
        /// </summary>
        public static string enumMoeda_HUF {
            get {
                return ResourceManager.GetString("enumMoeda_HUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RUPIA/INDONESIA.
        /// </summary>
        public static string enumMoeda_IDR {
            get {
                return ResourceManager.GetString("enumMoeda_IDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a SHEKEL/ISRAEL.
        /// </summary>
        public static string enumMoeda_ILS {
            get {
                return ResourceManager.GetString("enumMoeda_ILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RUPIA/INDIA.
        /// </summary>
        public static string enumMoeda_INR {
            get {
                return ResourceManager.GetString("enumMoeda_INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DINAR/IRAQUE.
        /// </summary>
        public static string enumMoeda_IQD {
            get {
                return ResourceManager.GetString("enumMoeda_IQD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RIAL/IRAN, REP.
        /// </summary>
        public static string enumMoeda_IRR {
            get {
                return ResourceManager.GetString("enumMoeda_IRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a COROA ISLND/ISLAN.
        /// </summary>
        public static string enumMoeda_ISK {
            get {
                return ResourceManager.GetString("enumMoeda_ISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR/JAMAICA.
        /// </summary>
        public static string enumMoeda_JMD {
            get {
                return ResourceManager.GetString("enumMoeda_JMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DINAR/JORDANIA.
        /// </summary>
        public static string enumMoeda_JOD {
            get {
                return ResourceManager.GetString("enumMoeda_JOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a IENE.
        /// </summary>
        public static string enumMoeda_JPY {
            get {
                return ResourceManager.GetString("enumMoeda_JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a XELIM/QUENIA.
        /// </summary>
        public static string enumMoeda_KES {
            get {
                return ResourceManager.GetString("enumMoeda_KES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a SOM QUIRGUISTAO.
        /// </summary>
        public static string enumMoeda_KGS {
            get {
                return ResourceManager.GetString("enumMoeda_KGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RIEL/CAMBOJA.
        /// </summary>
        public static string enumMoeda_KHR {
            get {
                return ResourceManager.GetString("enumMoeda_KHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a FRANCO/COMORES.
        /// </summary>
        public static string enumMoeda_KMF {
            get {
                return ResourceManager.GetString("enumMoeda_KMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a WON/COREIA NORTE.
        /// </summary>
        public static string enumMoeda_KPW {
            get {
                return ResourceManager.GetString("enumMoeda_KPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a WON COREIA SUL.
        /// </summary>
        public static string enumMoeda_KRW {
            get {
                return ResourceManager.GetString("enumMoeda_KRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DINAR/KWAIT.
        /// </summary>
        public static string enumMoeda_KWD {
            get {
                return ResourceManager.GetString("enumMoeda_KWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR CAYMAN.
        /// </summary>
        public static string enumMoeda_KYD {
            get {
                return ResourceManager.GetString("enumMoeda_KYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a TENGE CAZAQUISTAO.
        /// </summary>
        public static string enumMoeda_KZT {
            get {
                return ResourceManager.GetString("enumMoeda_KZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a QUIPE/LAOS, REP.
        /// </summary>
        public static string enumMoeda_LAK {
            get {
                return ResourceManager.GetString("enumMoeda_LAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LIBRA/LIBANO.
        /// </summary>
        public static string enumMoeda_LBP {
            get {
                return ResourceManager.GetString("enumMoeda_LBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RUPIA/SRI LANKA.
        /// </summary>
        public static string enumMoeda_LKR {
            get {
                return ResourceManager.GetString("enumMoeda_LKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR LIBERIA.
        /// </summary>
        public static string enumMoeda_LRD {
            get {
                return ResourceManager.GetString("enumMoeda_LRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LOTI/LESOTO.
        /// </summary>
        public static string enumMoeda_LSL {
            get {
                return ResourceManager.GetString("enumMoeda_LSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DINAR/LIBIA.
        /// </summary>
        public static string enumMoeda_LYD {
            get {
                return ResourceManager.GetString("enumMoeda_LYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DIRHAM/MARROCOS.
        /// </summary>
        public static string enumMoeda_MAD {
            get {
                return ResourceManager.GetString("enumMoeda_MAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LEU/MOLDAVIA, REP.
        /// </summary>
        public static string enumMoeda_MDL {
            get {
                return ResourceManager.GetString("enumMoeda_MDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a ARIARY MADAGASCAR.
        /// </summary>
        public static string enumMoeda_MGA {
            get {
                return ResourceManager.GetString("enumMoeda_MGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DINAR/MACEDONIA.
        /// </summary>
        public static string enumMoeda_MKD {
            get {
                return ResourceManager.GetString("enumMoeda_MKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a QUIATE/BIRMANIA.
        /// </summary>
        public static string enumMoeda_MMK {
            get {
                return ResourceManager.GetString("enumMoeda_MMK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a TUGRIK/MONGOLIA.
        /// </summary>
        public static string enumMoeda_MNT {
            get {
                return ResourceManager.GetString("enumMoeda_MNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a PATACA/MACAU.
        /// </summary>
        public static string enumMoeda_MOP {
            get {
                return ResourceManager.GetString("enumMoeda_MOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a UGUIA MAURITANIA.
        /// </summary>
        public static string enumMoeda_MRO {
            get {
                return ResourceManager.GetString("enumMoeda_MRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RUPIA/MAURICIO.
        /// </summary>
        public static string enumMoeda_MUR {
            get {
                return ResourceManager.GetString("enumMoeda_MUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RUFIA/MALDIVAS.
        /// </summary>
        public static string enumMoeda_MVR {
            get {
                return ResourceManager.GetString("enumMoeda_MVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a QUACHA/MALAVI.
        /// </summary>
        public static string enumMoeda_MWK {
            get {
                return ResourceManager.GetString("enumMoeda_MWK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a PESO/MEXICO.
        /// </summary>
        public static string enumMoeda_MXN {
            get {
                return ResourceManager.GetString("enumMoeda_MXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RINGGIT/MALASIA.
        /// </summary>
        public static string enumMoeda_MYR {
            get {
                return ResourceManager.GetString("enumMoeda_MYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a NOVA METICAL/MOCA.
        /// </summary>
        public static string enumMoeda_MZN {
            get {
                return ResourceManager.GetString("enumMoeda_MZN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR DA NAMIBIA.
        /// </summary>
        public static string enumMoeda_NAD {
            get {
                return ResourceManager.GetString("enumMoeda_NAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a NAIRA/NIGERIA.
        /// </summary>
        public static string enumMoeda_NGN {
            get {
                return ResourceManager.GetString("enumMoeda_NGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a CORDOBA OURO.
        /// </summary>
        public static string enumMoeda_NIO {
            get {
                return ResourceManager.GetString("enumMoeda_NIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a COROA NORUEGUESA.
        /// </summary>
        public static string enumMoeda_NOK {
            get {
                return ResourceManager.GetString("enumMoeda_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RUPIA/NEPAL.
        /// </summary>
        public static string enumMoeda_NPR {
            get {
                return ResourceManager.GetString("enumMoeda_NPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR/NOVA ZELAND.
        /// </summary>
        public static string enumMoeda_NZD {
            get {
                return ResourceManager.GetString("enumMoeda_NZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RIAL/OMA.
        /// </summary>
        public static string enumMoeda_OMR {
            get {
                return ResourceManager.GetString("enumMoeda_OMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a BALBOA/PANAMA.
        /// </summary>
        public static string enumMoeda_PAB {
            get {
                return ResourceManager.GetString("enumMoeda_PAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a NOVO SOL/PERU.
        /// </summary>
        public static string enumMoeda_PEN {
            get {
                return ResourceManager.GetString("enumMoeda_PEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a KINA/PAPUA N GUIN.
        /// </summary>
        public static string enumMoeda_PGK {
            get {
                return ResourceManager.GetString("enumMoeda_PGK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a PESO/FILIPINAS.
        /// </summary>
        public static string enumMoeda_PHP {
            get {
                return ResourceManager.GetString("enumMoeda_PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RUPIA/PAQUISTAO.
        /// </summary>
        public static string enumMoeda_PKR {
            get {
                return ResourceManager.GetString("enumMoeda_PKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a ZLOTY/POLONIA.
        /// </summary>
        public static string enumMoeda_PLN {
            get {
                return ResourceManager.GetString("enumMoeda_PLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a GUARANI/PARAGUAI.
        /// </summary>
        public static string enumMoeda_PYG {
            get {
                return ResourceManager.GetString("enumMoeda_PYG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RIAL/CATAR.
        /// </summary>
        public static string enumMoeda_QAR {
            get {
                return ResourceManager.GetString("enumMoeda_QAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a NOVO LEU/ROMENIA.
        /// </summary>
        public static string enumMoeda_RON {
            get {
                return ResourceManager.GetString("enumMoeda_RON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DINAR SERVIO SERVIA.
        /// </summary>
        public static string enumMoeda_RSD {
            get {
                return ResourceManager.GetString("enumMoeda_RSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RUBLO/RUSSIA.
        /// </summary>
        public static string enumMoeda_RUB {
            get {
                return ResourceManager.GetString("enumMoeda_RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a FRANCO/RUANDA.
        /// </summary>
        public static string enumMoeda_RWF {
            get {
                return ResourceManager.GetString("enumMoeda_RWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RIAL/ARAB SAUDITA.
        /// </summary>
        public static string enumMoeda_SAR {
            get {
                return ResourceManager.GetString("enumMoeda_SAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR IL SALOMAO.
        /// </summary>
        public static string enumMoeda_SBD {
            get {
                return ResourceManager.GetString("enumMoeda_SBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RUPIA/SEYCHELES.
        /// </summary>
        public static string enumMoeda_SCR {
            get {
                return ResourceManager.GetString("enumMoeda_SCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a NOVA LIBRA SUDANESA.
        /// </summary>
        public static string enumMoeda_SDG {
            get {
                return ResourceManager.GetString("enumMoeda_SDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DIREITO ESPECIAL.
        /// </summary>
        public static string enumMoeda_SDR {
            get {
                return ResourceManager.GetString("enumMoeda_SDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a COROA SUECA.
        /// </summary>
        public static string enumMoeda_SEK {
            get {
                return ResourceManager.GetString("enumMoeda_SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR CINGAPURA.
        /// </summary>
        public static string enumMoeda_SGD {
            get {
                return ResourceManager.GetString("enumMoeda_SGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LIBRA/STA HELENA.
        /// </summary>
        public static string enumMoeda_SHP {
            get {
                return ResourceManager.GetString("enumMoeda_SHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LEONE/SERRA LEOA.
        /// </summary>
        public static string enumMoeda_SLL {
            get {
                return ResourceManager.GetString("enumMoeda_SLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a XELIM/SOMALIA.
        /// </summary>
        public static string enumMoeda_SOS {
            get {
                return ResourceManager.GetString("enumMoeda_SOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR/SURINAME.
        /// </summary>
        public static string enumMoeda_SRD {
            get {
                return ResourceManager.GetString("enumMoeda_SRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LIBRA SUL SUDANESA.
        /// </summary>
        public static string enumMoeda_SSP {
            get {
                return ResourceManager.GetString("enumMoeda_SSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOBRA S TOME PRIN.
        /// </summary>
        public static string enumMoeda_STD {
            get {
                return ResourceManager.GetString("enumMoeda_STD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a COLON/EL SALVADOR.
        /// </summary>
        public static string enumMoeda_SVC {
            get {
                return ResourceManager.GetString("enumMoeda_SVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LIBRA/SIRIA, REP.
        /// </summary>
        public static string enumMoeda_SYP {
            get {
                return ResourceManager.GetString("enumMoeda_SYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LILANGENI/SUAZIL.
        /// </summary>
        public static string enumMoeda_SZL {
            get {
                return ResourceManager.GetString("enumMoeda_SZL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a BATH/TAILANDIA.
        /// </summary>
        public static string enumMoeda_THB {
            get {
                return ResourceManager.GetString("enumMoeda_THB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a SOMONI TADJIQUISTAO.
        /// </summary>
        public static string enumMoeda_TJS {
            get {
                return ResourceManager.GetString("enumMoeda_TJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a NOVO MANAT TURCOM.
        /// </summary>
        public static string enumMoeda_TMT {
            get {
                return ResourceManager.GetString("enumMoeda_TMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DINAR/TUNISIA.
        /// </summary>
        public static string enumMoeda_TND {
            get {
                return ResourceManager.GetString("enumMoeda_TND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a PAANGA/TONGA.
        /// </summary>
        public static string enumMoeda_TOP {
            get {
                return ResourceManager.GetString("enumMoeda_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a LIRA TURCA.
        /// </summary>
        public static string enumMoeda_TRY {
            get {
                return ResourceManager.GetString("enumMoeda_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR/TRIN. TOBAG.
        /// </summary>
        public static string enumMoeda_TTD {
            get {
                return ResourceManager.GetString("enumMoeda_TTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a NOVO DOLAR/TAIWAN.
        /// </summary>
        public static string enumMoeda_TWD {
            get {
                return ResourceManager.GetString("enumMoeda_TWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a XELIM/TANZANIA.
        /// </summary>
        public static string enumMoeda_TZS {
            get {
                return ResourceManager.GetString("enumMoeda_TZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a HRYVNIA UCRANIA.
        /// </summary>
        public static string enumMoeda_UAH {
            get {
                return ResourceManager.GetString("enumMoeda_UAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a XELIM/UGANDA.
        /// </summary>
        public static string enumMoeda_UGX {
            get {
                return ResourceManager.GetString("enumMoeda_UGX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR DOS EUA.
        /// </summary>
        public static string enumMoeda_USD {
            get {
                return ResourceManager.GetString("enumMoeda_USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a PESO/URUGUAIO.
        /// </summary>
        public static string enumMoeda_UYU {
            get {
                return ResourceManager.GetString("enumMoeda_UYU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a SOM UZBEQUISTAO.
        /// </summary>
        public static string enumMoeda_UZS {
            get {
                return ResourceManager.GetString("enumMoeda_UZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a BOLIVAR VEN.
        /// </summary>
        public static string enumMoeda_VEF {
            get {
                return ResourceManager.GetString("enumMoeda_VEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DONGUE/VIETNAN.
        /// </summary>
        public static string enumMoeda_VND {
            get {
                return ResourceManager.GetString("enumMoeda_VND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a VATU VANUATU.
        /// </summary>
        public static string enumMoeda_VUV {
            get {
                return ResourceManager.GetString("enumMoeda_VUV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a TALA SAMOA.
        /// </summary>
        public static string enumMoeda_WST {
            get {
                return ResourceManager.GetString("enumMoeda_WST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a FRANCO CFA BEAC.
        /// </summary>
        public static string enumMoeda_XAF {
            get {
                return ResourceManager.GetString("enumMoeda_XAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR OURO.
        /// </summary>
        public static string enumMoeda_XAU {
            get {
                return ResourceManager.GetString("enumMoeda_XAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR CARIBE ORIENTAL.
        /// </summary>
        public static string enumMoeda_XCD {
            get {
                return ResourceManager.GetString("enumMoeda_XCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a UNID.MONET.EUROP..
        /// </summary>
        public static string enumMoeda_XEU {
            get {
                return ResourceManager.GetString("enumMoeda_XEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a FRANCO CFA BCEAO.
        /// </summary>
        public static string enumMoeda_XOF {
            get {
                return ResourceManager.GetString("enumMoeda_XOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a FRANCO CFP.
        /// </summary>
        public static string enumMoeda_XPF {
            get {
                return ResourceManager.GetString("enumMoeda_XPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RIAL/IEMEN.
        /// </summary>
        public static string enumMoeda_YER {
            get {
                return ResourceManager.GetString("enumMoeda_YER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a RANDE/AFRICA SUL.
        /// </summary>
        public static string enumMoeda_ZAR {
            get {
                return ResourceManager.GetString("enumMoeda_ZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a QUACHA ZAMBIA.
        /// </summary>
        public static string enumMoeda_ZMW {
            get {
                return ResourceManager.GetString("enumMoeda_ZMW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a DOLAR ZIMBABUE.
        /// </summary>
        public static string enumMoeda_ZWL {
            get {
                return ResourceManager.GetString("enumMoeda_ZWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Alterar.
        /// </summary>
        public static string enumTipoAcao_Alterar {
            get {
                return ResourceManager.GetString("enumTipoAcao_Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Excluir.
        /// </summary>
        public static string enumTipoAcao_Excluir {
            get {
                return ResourceManager.GetString("enumTipoAcao_Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Incluir.
        /// </summary>
        public static string enumTipoAcao_Incluir {
            get {
                return ResourceManager.GetString("enumTipoAcao_Incluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma seqüência de caracteres localizada semelhante a Visualizar.
        /// </summary>
        public static string enumTipoAcao_Visualizar {
            get {
                return ResourceManager.GetString("enumTipoAcao_Visualizar", resourceCulture);
            }
        }
    }
}
